### Generate test data table with 50 records
POST http://localhost:8181/api/fakermaker/dataTable/
Content-Type: application/json

{
  "sessionID": "123123123234l",
  "fakers": [
    "Harry Potter",
    "Lord of the Rings"
  ],
  "makers": [
    {
      "makerEnum": "First Name",
      "nickname": "first name",
      "nullable": false
    },
    {
      "makerEnum": "Last Name",
      "nickname": "last name",
      "nullable": false
    },
    {
      "makerEnum": "Company Name",
      "nickname": "company name",
      "nullable": false
    },
    {
      "makerEnum": "Email",
      "nickname": "email",
      "nullable": true
    },
    {
      "makerEnum": "Phone Number",
      "nickname": "phone",
      "nullable": false
    },
    {
      "makerEnum": "Address",
      "nickname": "address",
      "nullable": false
    },
    {
      "makerEnum": "Address 2",
      "nickname": "address2",
      "nullable": false
    },
    {
      "makerEnum": "State",
      "nickname": "state",
      "nullable": false
    },
    {
      "makerEnum": "City",
      "nickname": "city",
      "nullable": false
    },
    {
      "makerEnum": "Zip",
      "nickname": "zip",
      "nullable": false
    },
    {
      "makerEnum": "Price",
      "nickname": "price",
      "nullable": false,
      "priceRange": [
        12.99,
        100.24
      ]
    },
    {
      "makerEnum": "Number",
      "nickname": "number of pets",
      "nullable": false,
      "numberRange": [
        "1",
        "2"
      ]
    },
    {
      "makerEnum": "Date",
      "dateRange": [
        "JAN-01-1970",
        "FEB-04-2006"
      ],
      "nickname": "birthday",
      "nullable": false
    },
    {
      "makerEnum": "True/False",
      "nickname": "is attending",
      "nullable": false
    },
    {
      "makerEnum": "Id",
      "idTypeEnum" : "UUID",
      "nickname": "itemId",
      "nullable": false
    },
    {
      "makerEnum": "Credit Card",
      "nickname": "card number",
      "nullable": false
    },
    {
      "makerEnum": "Credit Card CVV",
      "nickname": "card CVV",
      "nullable": false
    }
  ]
}

### Download 1M records with specified schema
POST http://localhost:8181/api/fakermaker/csv/1000000
Content-Type: application/json

{
  "sessionID": "123123123234l",
  "fakers": [
    "Harry Potter",
    "Lord of the Rings"
  ],
  "makers": [
    {
      "makerEnum": "First Name",
      "nickname": "first name",
      "nullable": false
    },
    {
      "makerEnum": "Last Name",
      "nickname": "last name",
      "nullable": false
    },
    {
      "makerEnum": "Email",
      "nickname": "email",
      "nullable": true
    },
    {
      "makerEnum": "Phone Number",
      "nickname": "phone",
      "nullable": false
    },
    {
      "makerEnum": "Address",
      "nickname": "address",
      "nullable": false
    },
    {
      "makerEnum": "Address 2",
      "nickname": "address2",
      "nullable": false
    },
    {
      "makerEnum": "State",
      "nickname": "state",
      "nullable": false
    },
    {
      "makerEnum": "City",
      "nickname": "city",
      "nullable": false
    },
    {
      "makerEnum": "Zip",
      "nickname": "zip",
      "nullable": false
    },
    {
      "makerEnum": "Price",
      "nickname": "price",
      "nullable": false,
      "priceRange": [
        12.99,
        100.24
      ]
    },
    {
      "makerEnum": "Number",
      "nickname": "number of pets",
      "nullable": false,
      "numberRange": [
        "1",
        "2"
      ]
    },
    {
      "makerEnum": "Date",
      "dateRange": [
        "JAN-01-1970",
        "FEB-04-2006"
      ],
      "nickname": "birthday",
      "nullable": false
    },
    {
      "makerEnum": "True/False",
      "nickname": "is attending",
      "nullable": false
    },
    {
      "makerEnum": "Id",
      "idTypeEnum" : "UUID",
      "nickname": "itemId",
      "nullable": false
    },
    {
      "makerEnum": "Credit Card",
      "nickname": "card number",
      "nullable": false
    },
    {
      "makerEnum": "Credit Card",
      "nickname": "card number",
      "nullable": false
    },
    {
      "makerEnum": "Credit Card CVV",
      "nickname": "card CVV",
      "nullable": false
    }
  ]
}

### Retrieve available schema definitions
GET http://localhost:8181/api/fakermaker/fakermakers