package elias.fakerMaker.fakers.tvshows

object BreakingBad {
    val characters = listOf(
        // Main Cast
        "Walter White",
        "Jesse Pinkman",
        "Skyler White",
        "Hank Schrader",
        "Marie Schrader",
        "Walter White Jr.",
        "Gustavo Fring",
        "Saul Goodman",
        "Mike Ehrmantraut",
        "Lydia Rodarte-Quayle",
        "Todd Alquist",
        // Supporting Characters
        "Steven Gomez",
        "Skinny Pete",
        "Ted Beneke",
        "Brandon 'Badger' Mayhew",
        "Huell Babineaux",
        "George Merkert",
        "Tyrus Kitt",
        "Andrea Cantillo",
        "Carmen Molina",
        "Jane Margolis",
        "Hector Salamanca",
        "Gale Boetticher",
        "Jack Welker",
        "Kenny",
        "Leonel Salamanca",
        "Gretchen Schwartz",
        "Marco Salamanca",
        "Patrick Kuby",
        "Clovis",
        "Diane Pinkman",
        "Donald Margolis",
        "Gaff",
        "Tim Roberts",
        "Tuco Salamanca",
        "Adam Pinkman",
        "Declan",
        "Dennis Markowski",
        "Detective Kalanchoe",
        "Elliott Schwartz",
        "Juan Bolsa",
        "Krazy-8",
        "Pamela Orbic",
        "Wendy",
        // Additional Characters
        "Brock Cantillo",
        "Victor",
        "Francesca Liddy",
        "Dr. Delcavoli",
        "Kaylee Ehrmantraut",
        "Bogdan Wolynetz",
        "Matt",
        "Frankie",
        "Lester",
        "Combo",
        "Austin Ramey",
        "Hugo Archilleya",
        "Chad",
        "Cynthia",
        "Duane Chow",
        "Louis Corbett",
        "Ed Galbraith",
        "Gonzo",
        "No-Doze",
        "Old Joe",
        "Jake Pinkman",
        "Stacey Ehrmantraut",
        "Kiira Rodarte-Quayle",
        "Joaquin Salamanca",
        "Lalo Salamanca",
        "Jimmy McGill",
        "Barry Goodman",
        "Benicio Fuentes",
        "Blanca Gomez",
        "Carol",
        "Cesar",
        "Dr. Chavez",
        "Chuck",
        "Isaac Conley",
        "Dana Cortez",
        "Dave",
        "Declan's Cook",
        "Declan's Driver",
        "Delores",
        "Denise",
        "Stephanie Doswell",
        "Fernando",
        "Ron Forenall",
        "Fran",
        "Mr. Gardiner",
        "Gary",
        "Getz",
        "Ginny",
        "M. Hansen",
        "Harry Lipenstein",
        "Herzog",
        "Scott Hoffman",
        "Andrew Holt",
        "Ira",
        "Irving",
        "Janice",
        "Jill",
        "Jimmy",
        "John",
        "Andrew Kaufman",
        "Bobby Kee",
        "Ken",
        "Ma Kettle",
        "Pa Kettle",
        "James Kilkelly",
        "Emilio Koyama",
        "Lawson",
        "Lucy",
        "Luis",
        "Jeff Maher",
        "Chris Mara",
        "Margaret",
        "Mariano",
        "Raymond Martinez",
        "Jack McGann",
        "Michael Kilbourne",
        "Miguel",
        "Mr. Molina",
        "William Moniz",
        "Munn",
        "Jodi Nichols",
        "Nick",
        "Mrs. Ortega",
        "Van Oster",
        "Paco",
        "Papadoumian",
        "Patrick",
        "Patty Lin",
        "Dog Paulson",
        "Peng",
        "Anthony Perez",
        "Mrs. Peyketewa",
        "James Picarus",
        "Mr. Pike",
        "Poochy",
        "Mrs. Pope",
        "Renaldo",
        "Ricky",
        "Charlie Rose",
        "Russell",
        "Sandor",
        "Saxton"
    )

    val companies = listOf(
        // Major Companies
        "Los Pollos Hermanos",
        "Gray Matter Technologies",
        "Madrigal Electromotive GmbH",
        "Beneke Fabricators",
        "Saul Goodman & Associates",
        "A1A Car Wash",
        "Vamonos Pest",
        "Ice Station Zebra Associates",
        // Industrial/Chemical Companies
        "Gus's Industrial Laundry",
        "Golden Moth Chemical",
        "Schuler Chemical Supply",
        "Chow's Chemical Warehouse",
        // Front Companies
        "Lavandería Brillante",
        "Pollos Hermanos Distribution",
        "ASAC Mining Company",
        "Casa Tranquila Nursing Home",
        // Retail/Service Businesses
        "JP Wynne High School",
        "Crossroads Motel",
        "Octopus Car Wash",
        "Save-Rite Drugs",
        "Tampico Furniture",
        "Danny's Auto Service",
        "Old Joe's Salvage Yard",
        "Best Quality Vacuum Repair",
        // Small Businesses
        "Bogdan's Car Wash",
        "Clovis's Auto Repair",
        "Jesse's RV Rental",
        // Restaurants/Food
        "Taco Sal",
        "Garduno's Restaurant",
        "El Michoacano Restaurant",
        "The Grove Café",
        "Loyola's Family Restaurant",
        // Hotels/Motels
        "Crystal Palace Hotel",
        "Plaza Hotel",
        "Beachcomber Inn",
        "Crossroads Motel",
        // Medical Facilities
        "Wachovia Medical Center",
        "Sacred Heart Hospital",
        "On the Mend Physical Therapy",
        // Financial Institutions
        "Cradock Marine Bank",
        "Mesa Credit Union",
        "First National Bank",
        // Legal/Professional Services
        "HHM Law Firm",
        "Ehrmantraut Security Services",
        "White & Associates",
        // Shipping/Transportation
        "Madrigal Freight",
        "ABQ In & Out Storage",
        "Southwest Aniline",
        // Entertainment
        "Lazer Base",
        "Paul's Coin Company",
        "The Dog House"
    )
}