package elias.fakerMaker.fakers.tvshows

object DoctorWho {
    val characters = listOf(
        // Time Lords/Ladies
        "The Master",
        "Rassilon",
        "Romana",
        "The Rani",
        "Omega",
        "The Monk",
        "The War Chief",
        "The Valeyard",
        "The Corsair",
        "Borusa",
        "Rodan",
        "Andred",
        "The Castellan",
        "Flavia",
        "Hedin",
        "The Inquisitor",
        "Maxil",
        "Thalia",
        "Cardinal Zorac",
        // Classic Companions
        "Susan Foreman",
        "Ian Chesterton",
        "Barbara Wright",
        "Vicki",
        "Steven Taylor",
        "Dodo Chaplet",
        "Polly Wright",
        "Ben Jackson",
        "Jamie McCrimmon",
        "Victoria Waterfield",
        "Zoe Heriot",
        "Liz Shaw",
        "Jo Grant",
        "Sarah Jane Smith",
        "Harry Sullivan",
        "Leela",
        "K9",
        "Romana I",
        "Romana II",
        "Adric",
        "Nyssa",
        "Tegan Jovanka",
        "Vislor Turlough",
        "Kamelion",
        "Peri Brown",
        "Mel Bush",
        "Ace",
        // Modern Companions
        "Rose Tyler",
        "Adam Mitchell",
        "Jack Harkness",
        "Mickey Smith",
        "Martha Jones",
        "Donna Noble",
        "Amy Pond",
        "Rory Williams",
        "Clara Oswald",
        "Bill Potts",
        "Nardole",
        "Graham O'Brien",
        "Ryan Sinclair",
        "Yasmin Khan",
        "Dan Lewis",
        "Ruby Sunday",
        "Ncuti Gatwa's Companion",
        // Supporting Characters
        "Jackie Tyler",
        "Pete Tyler",
        "Wilfred Mott",
        "Sylvia Noble",
        "Brian Williams",
        "Kate Stewart",
        "Osgood",
        "Jenny Flint",
        "Madame Vastra",
        "Strax",
        "Craig Owens",
        "Sophie Owens",
        "Danny Pink",
        "Grace O'Brien",
        "River Song",
        "Jenny",
        "Christina de Souza",
        "Astrid Peth",
        "Jackson Lake",
        "Adelaide Brooke",
        "Sally Sparrow",
        "Joan Redfern",
        "Harriet Jones",
        "Lucy Saxon",
        "Francine Jones",
        "Tish Jones",
        "Leo Jones",
        "Clyde Langer",
        "Luke Smith",
        "Maria Jackson",
        "Rani Chandra",
        "Sky Smith",
        // Villains
        "Davros",
        "The Cyber-Controller",
        "The Great Intelligence",
        "Madame Kovarian",
        "Missy",
        "The Silence",
        "Morbius",
        "The Black Guardian",
        "The White Guardian",
        "The Celestial Toymaker",
        "The Dream Lord",
        "Fenric",
        "The Beast",
        "House",
        "Tasha Lem",
        "Madame Delphox",
        "Margaret Blaine",
        "Max Capricorn",
        "Henry van Statten",
        "John Lumic",
        "Brother Lassar",
        "Professor Zaroff",
        "Magnus Greel",
        "Mehendri Solon",
        "Harrison Chase",
        "Eldrad",
        "Count Federico",
        "The Master of the Land of Fiction",
        // Recurring Species Leaders
        "Supreme Dalek",
        "Cyber-Leader",
        "Sontaran Commander Linx",
        "Sontaran Commander Stor",
        "Ice Lord Slaar",
        "Sea Devil Leader",
        "Silurian Leader Okdel",
        "Zygon Leader",
        // UNIT Personnel
        "Brigadier Lethbridge-Stewart",
        "Sergeant Benton",
        "Mike Yates",
        "Colonel Mace",
        "Captain Carter",
        "Captain Erisa Magambo",
        "Private Ross Jenkins",
        "Colonel Winters",
    )

    val companies = listOf(
        "Torchwood Institute",
        "UNIT",
        "International Electromatics",
        "Global Chemicals",
        "ThinkTank",
        "H.C. Clements",
        "Cybus Industries",
        "Adipose Industries",
        "Rattigan Academy",
        "ATMOS Industries",
        "Lazarus Laboratories",
        "Bad Wolf Corporation",
        "GeoComTex",
        "Van Statten Industries",
        "Powell Estate",
        "Copper's Hill",
        "The Pantheon of Discord",
        "Magpie Electricals",
        "Wessex Defence",
        "Planet 3",
        "International Gallery",
        "Global Technological Development",
        "Fetch Priory",
        "Bi-Al Foundation",
        "Alternative 3",
        "Space World",
        "Axos Corporation",
        "Inferno Project",
        "Scientific Reform Society",
        "Tranquil Repose",
        "Satellite Five",
        "Department C19",
        "3W",
        "St Luke's University",
        "Coal Hill School/Academy",
        "Naismith Institute",
        "Union of Traitors"
    )
}