package elias.fakerMaker.fakers.tvshows

object Monk {
    val characters = listOf(
        "Aaron Hayden",
        "Aaron Larkin",
        "Aaron Polanski",
        "Abigail Carlyle",
        "Abigail Guthrie",
        "Adam Kirk",
        "Adrian Monk",
        "Agent Lapides",
        "Agent Stone",
        "Agnes Monk",
        "Al Nicoletto",
        "Alameda",
        "Alan Carnegie",
        "Alby Drake",
        "Alice Westergren",
        "Allison Clark",
        "Amanda Babbage",
        "Amber Post",
        "Ambrose Monk",
        "Angela Dirks",
        "Angeline Dilworth",
        "Angie DeLuca",
        "Anna Pollard",
        "Ansara Waingaya",
        "Archie Modine",
        "Arleen Cassidy",
        "Arlene Boras",
        "Barbara O'Keefe",
        "Ben Glaser",
        "Ben Gruber",
        "Benjy Fleming",
        "Bennie Wentworth",
        "Beth Landow",
        "Bill Gibbard",
        "Bill LaFrankie",
        "Billy Logan",
        "Bob Costas",
        "Bobby Davenport",
        "Boz Harrelson",
        "Brad Terry",
        "Bradley Foster",
        "Brandon Lorber",
        "Brandy Barber",
        "Brent Donovan",
        "Brian Babbage",
        "Brian Binsack",
        "Brian Lemmon",
        "Brian Willis",
        "Brother Andrew",
        "Cal Gefsky",
        "Callie Esterhaus",
        "Cameron",
        "Carl Bates",
        "Carol Maloney",
        "Carolyn Walsh",
        "Cassie Drake",
        "Catherine Lavinio",
        "Chance Singer",
        "Charles Bach",
        "Charles Friedken",
        "Charles Kroger",
        "Cheryl Fleming",
        "Chet Walsh",
        "Chip Rosati",
        "Chloe Blackburn",
        "Chris Downey",
        "Christiaan Vezza",
        "Christine Rapp",
        "Christine Rutherford",
        "Cindy Chow",
        "Clara Toplyn",
        "Clarence Stanton",
        "Colmes",
        "Conrad Gould",
        "Cora Little",
        "Crystal Smith",
        "Cyrus Canning",
        "Dale J. Biederbeck III",
        "Dalton Padron",
        "Daniel MacGraw",
        "Daniel Reese",
        "Daniel Thorn",
        "Daniela Grace",
        "Danielle Hossack",
        "Danny Weaver",
        "Darnell Rudner",
        "Darrell Cain",
        "Darren Leveroni",
        "Darryl Wright",
        "David Gitelson",
        "David Ruskin",
        "David Sobin",
        "Davis Scott",
        "Dean Berry",
        "Debbie Barnett",
        "Del Johnston",
        "Dennis Gammill",
        "Denny Graf",
        "Denny Hodges",
        "Denny Jardeen",
        "Derek Philby",
        "Derek Thorpe",
        "Dewey Albert",
        "Dewey Jordan",
        "Dexter Larson",
        "Diane Truby",
        "Dianne Brooks",
        "Dimitry Kreslov",
        "Dolly Flint",
        "Douglas Fleming",
        "Douglas Thurman",
        "Dwight Ellison",
        "Dylan Swift",
        "Eddie Dial",
        "Eddie Murdoch",
        "Edgar Heinz",
        "Edith Capriani",
        "Edna Coruthers",
        "Edward Stilson",
        "Eileen Hill",
        "Elliot D'Souza",
        "Erin Hammond",
        "Ethan Rickover",
        "Evan Coker",
        "Evan Gildea",
        "Francis Merrigan",
        "Frank DePalma",
        "Frank Nunn",
        "Frank Porter",
        "Frank Prager",
        "Frank Pulaski",
        "Frank Ruttle",
        "Frank Willis",
        "Gail Fleming",
        "Gail Segalis",
        "Garrett Price",
        "Gavin Lloyd",
        "George Gionopolis",
        "George Rowe",
        "George Teeger",
        "Gerald Vengal",
        "Gladys Aquino",
        "Gladys Menchen",
        "Griffin Briggs",
        "Gwen Zaleski",
        "Hadley Jorgenson",
        "Hal Duncan",
        "Hal Tucker",
        "Hank Johansen",
        "Harold Krenshaw",
        "Harold Maloney",
        "Harrison Powell",
        "Harry Ashcombe",
        "Harvey Disher",
        "Hector Morales",
        "Heidi Gefsky",
        "Henry Rutherford",
        "Hiram Holling",
        "Howard Fleming",
        "Howard Gordon",
        "Ian Agnew",
        "Ian Blackburn",
        "Ian Sykes",
        "Ike",
        "J.J. the Joke Machine",
        "Jack Bollinger",
        "Jack Leverett",
        "Jack Monk",
        "Jack Monk Jr.",
        "Jack Whitman",
        "Jack Wyatt",
        "Jacob Posner",
        "Jake Phillips",
        "James Duffy",
        "James Novak",
        "Janet Novak",
        "Janice Ellinghouse",
        "Jared Stottlemeyer",
        "Jason Ronstadt",
        "Jasper Perry",
        "Jay Bennett",
        "Jenna Ryan",
        "Jennie Silverman",
        "Jennie Zeppettelli",
        "Jeremiah Cowan",
        "Jimmy Barlowe",
        "Jimmy Belmont",
        "Jimmy Botsdale",
        "Jimmy Cusack",
        "Jimmy Lu",
        "Joanne Raphelson",
        "Joe Christie",
        "Joe Cochran"
    )

    val companies = listOf(
        // Major Companies
        "Trudy's Chronicle",
        "San Francisco Telegraph",
        "St. Claire's Hospital",
        "Hosterman and Associates",
        "Powell's Construction",
        // Retail & Services
        "Happy Valley Shopping Mall",
        "Ralph's Pharmacy",
        "Willie's Dry Cleaning",
        "Water & Power",
        "Cobra Gym",
        "Tie Rack",
        // Food & Dining
        "Monica's Cafe",
        "Joe's Bar",
        "Monk's Diner",
        "Greek Restaurant",
        "La Pasteria",
        // Entertainment
        "KPIX Channel 5",
        "Bay Area Radio",
        "Urban Freedom Records",
        "West Coast Theater",
        "Heritage Theater",
        // Financial Institutions
        "First California Bank",
        "Bay Area Savings and Loan",
        "Pacific Trust",
        "Hamilton Trust Bank",
        // Technology Companies
        "Mega-Byte",
        "Computer Renaissance",
        "Ellison Software",
        "Pertronics",
        // Security Companies
        "Intertect Security",
        "Leland Security Systems",
        "Diamond Security",
        // Legal Firms
        "Stottlemeyer & Associates",
        "Harrison, Powell & Schwartzman",
        "Rickover & Associates",
        // Transportation
        "Yellow Cab Company",
        "Bay Area Transit",
        "Golden State Bus Lines",
        // Real Estate
        "Breen Properties",
        "Summit Realty",
        "Bay Area Properties",
        // Miscellaneous Businesses
        "Natalie's Cleaning Service",
        "Independent Mercantile",
        "City Gas & Electric",
        "Superior Storage",
        "Maritime Museum Gift Shop"
    )
}