package elias.fakerMaker.fakers.tvshows

object ParksAndRec {
    val characters = listOf(
        "Al Connor",
        "Allison Gliffert",
        "Andy Dwyer",
        "Ann Perkins",
        "April Ludgate",
        "Artie",
        "August Clementine",
        "Aunt Tilda Bird",
        "Ben",
        "Beth",
        "Bill Dexhart",
        "Bill Haggerty",
        "Bjorn Lerpiss",
        "Bobby Newport",
        "Brandi Maxxxx",
        "Brett Hull",
        "Burly",
        "Burt Macklin",
        "Carl",
        "Carl Lorthner",
        "Champion",
        "Chance Frenlm",
        "China Joe",
        "Chipp McCapp",
        "Chris",
        "Clarence Carrington",
        "Councilman Pillner",
        "Courtney",
        "Craig",
        "Craig Middlebrooks",
        "Crazy Ira",
        "Dakota Newport",
        "David Murray",
        "David Moser",
        "David Sanderson",
        "Dawn Krink",
        "Dennis Feinstein",
        "Dennis Lerpiss",
        "Denver Newport",
        "Derek",
        "Derry Murbles",
        "Dewey",
        "Diane Lewis",
        "DJ Roomba",
        "Donna Meagle",
        "Douglass Howser",
        "Dr. Harris",
        "Dr. Richard Nygard",
        "Ed",
        "Eddie",
        "Eduardo",
        "Elizabeth",
        "Ellis",
        "Elsa Clack",
        "Elvis Correja",
        "Emily",
        "Ethel Beavers",
        "Eugene Dredge",
        "Fairway Frank",
        "Fielding Milton",
        "Frank Beckerson",
        "Frank Mann",
        "Freddy",
        "Garry Gergich",
        "Garth Blundin",
        "Gayle Gergich",
        "Geoffrey Morglesberg",
        "George Gernway",
        "George Williams",
        "Ginuwine",
        "Gladys Gergich",
        "Grant Larson",
        "Greg Pikitis",
        "Gregory",
        "Gretel",
        "Hank Muntak",
        "Harris",
        "Henry Wyatt",
        "Herb Scaifer",
        "Herman Lerpiss",
        "Horace Rangel",
        "Howard Kurtzwilder",
        "Howard Tuttleman",
        "Hugh Trumple",
        "Ian Winston",
        "Ingrid de Forest",
        "Ivy Lewis",
        "Jack Cooper",
        "Jack Dwyer",
        "James Pierson",
        "Janet Snakehole",
        "Janet Trungle",
        "Jean-Ralphio Saperstein",
        "Jeanine Restrepo",
        "Jennifer Barkley",
        "Jeremy Jamm",
        "Jessica Wicks",
        "Jhonny Qujada",
        "Jim Kabernick",
        "JJ Lipscomb",
        "Joan Callamezzo",
        "Joe",
        "Joe Biden",
        "Joe Campopiano",
        "Joe Fantringham",
        "Joey",
        "Johnny Karate",
        "Jon Swanson",
        "Judy Hitler",
        "Julia Wyatt",
        "Justin Anderson",
        "Kate Speevak",
        "Kathryn Pinewood",
        "Keef Slertner",
        "Kelly Larson",
        "Ken Hotate",
        "Kevin",
        "Kiley",
        "Kim Terlando",
        "Kyle",
        "Larry Ludgate",
        "Lauren Burkiss",
        "Lavondrius Meagle",
        "Lawrence",
        "Len Hugeff",
        "Leonard Tchulm",
        "Leslie Knope",
        "Leslie Perkins-Traeger",
        "Li'l Sebastian",
        "Linda Lonegan",
        "Lindsay Carlisle Shay",
        "Lon Swanson",
        "Lord Edgar Covington",
        "Lucy Santo Domingo",
        "Madison",
        "Manrico Della Rossa",
        "Marci",
        "Marcia Langman",
        "Marcus Everret Langly",
        "Maria Portlesman",
        "Mark Brendanawicz",
        "Marlene Griggs-Knope",
        "Marshall Langman",
        "Martin Housely",
        "Martin Kernston",
        "Mayor Stice",
        "Mel",
        "Michael Chang",
        "Michael Holloway",
        "Michael Tansley",
        "Mike",
        "Millicent Gergich",
        "Miriam Gergich",
        "Mona-Lisa Saperstein",
        "Morris Lerpiss",
        "Muriel",
        "Nadia Stasky",
        "Natalie Ludgate",
        "Nathaniel Bixby Mark",
        "Ned Jones",
        "Nick Newport, Jr.",
        "Nick Newport, Sr.",
        "Old Gus",
        "Oliver Perkins-Traeger",
        "Oliver Traeger",
        "Orin",
        "Paul Iaresco",
        "Pearl",
        "Perd Hapley",
        "Pete Disellio",
        "Phil"
    )

    val locations = listOf(
        "Animal Control",
        "City Council Chamber",
        "City Hall",
        "Eagleton",
        "Entertainment 720",
        "Food and Stuff",
        "Grain 'n Simple",
        "Grizzl Headquarters",
        "Harvest Festival Grounds",
        "Harvey James Park",
        "JJ's Diner",
        "Kernston's Rubber Nipples",
        "Leslie's House",
        "Lot 48",
        "Paunch Burger",
        "Pawnee Animal Hospital",
        "Pawnee Commons",
        "Pawnee Emergency Response Center",
        "Pawnee City Hall",
        "Pawnee Farmer's Market",
        "Pawnee Journal Building",
        "Pawnee Municipal Golf Course",
        "Pawnee Racquet Club",
        "Pawnee River",
        "Pawnee Zoo",
        "Pawneeland",
        "Pioneer Hall",
        "Ramsett Park",
        "Ron's Cabin",
        "Snakehole Lounge",
        "St. Joseph Hospital",
        "Sullivan Street Pit",
        "The Bulge",
        "The Glitter Factory",
        "The Quiet Corn",
        "Tom's Bistro",
        "Turnbill Mansion",
        "Wamapoke Casino",
        "William H. Harrison Museum"
    )

    val companies = listOf(
        // Major Corporations
        "Sweetums",
        "Gryzzl",
        "Paunch Burger",
        "Entertainment 720",
        "Very Good Building & Development Co.",
        "Rent-A-Swag",
        "Lady Foot Locker",
        "Kernston's Rubber Nipples",
        // Media Companies
        "Pawnee Journal",
        "Pawnee Sun",
        "Pawnee Today",
        "Channel 4 News",
        "93.7: The Douche",
        "Crazy Ira and The Douche Radio Show",
        // Restaurants and Food Services
        "JJ's Diner",
        "The Snakehole Lounge",
        "Food and Stuff",
        "Sue's Salads",
        "Tom's Bistro",
        "The Bulge",
        "Grain 'n Simple",
        "Big Head Joe's",
        // Small Businesses
        "Tilton & Radomski Accounting",
        "Dennis's Beepers",
        "Jurassic Fork",
        "Sub Club",
        "Wamapoke Casino",
        // Failed/Temporary Businesses
        "Low-Cal Calzone Zone",
        "Tommy Fresh",
        "Pawnee VideoDome",
        "Dr. Richard Nygard's Practice",
        "Pound Town",
        // Online/Tech Companies
        "The Cloudy Cloud",
        "Know Ya Boo",
        "E-Phone",
        // Chains/Franchises
        "Borders",
        "Blockbuster",
        "Harvey James",
        // Event Planning/Entertainment
        "Essence of Twilight",
        "Ultimate Party Zone",
        "The Glitter Factory",
        // Manufacturing
        "Hammer Mill",
        "Newport Living and Leisure"
    )

}