package elias.fakerMaker.fakers.tvshows

object TheOffice {
    val characters = listOf(
        "A.J.",
        "Abby",
        "Alan",
        "Alan Brand",
        "Alex",
        "Alice",
        "Amy",
        "Andy Bernard",
        "Andy Roddick",
        "Angela Martin",
        "Angelo Grotti",
        "Arnie Rissman",
        "Ashley",
        "Astrid Levinson",
        "Bandit",
        "Barbara Allen",
        "Barbara Keevis",
        "Belsnickel",
        "Bert California",
        "Bert Jacobs",
        "Betsy Halpert",
        "Bill Cress",
        "Bill Hader",
        "Billy Merchant",
        "Billy the Bartender",
        "Blind Guy McSqueezy",
        "Bob Vance",
        "Brandon",
        "Brenda Matlowe",
        "Brian Wittle",
        "Broccoli Rob",
        "Bruce",
        "Captain Jack",
        "Carla",
        "Carla Fern",
        "Carol Stills",
        "Casey Dean",
        "Catherine Zeta-Scarn",
        "Cathy Becker",
        "Cathy Simms",
        "Cecelia Halpert",
        "Chad Ligh",
        "Charles Miner",
        "Cherokee Jack",
        "Chet Montgomery",
        "Chris Finch",
        "Chris Kotter",
        "Christian",
        "Christian Slater",
        "Clark Green",
        "Colin",
        "Conan O'Brien",
        "Concierge Marie",
        "Craig",
        "Creed Bratton",
        "Cynthia",
        "Dan Gore",
        "Daniel Donnelly",
        "Danny Cordray",
        "Darryl Philbin",
        "David Brent",
        "David Wallace",
        "Dawn Tinsley",
        "Deangelo Vickers",
        "Debbie Brown",
        "Debby Donnelly",
        "Deborah Shoshlefski",
        "Dennis",
        "Devon White",
        "Diane Kelly",
        "Donna Newton",
        "Drake Howard",
        "Dwight Schrute",
        "Ed Truck",
        "Edward R. Meow",
        "Elbert Lapin",
        "Eldred",
        "Elizabeth",
        "Ellen Bernard",
        "Eric",
        "Eric Ward",
        "Erik",
        "Erin Hannon",
        "Esther Bruegger",
        "Evan",
        "Fannie Schrute",
        "Fern Widgale",
        "Frank",
        "Fred Henry",
        "Gabe Lewis",
        "Garbage",
        "Gareth Keenan",
        "Gerald Halpert",
        "Gideon",
        "Gil",
        "Gino",
        "Glenn",
        "Goldenface",
        "Gordon",
        "Grace",
        "Gwyneth Philbin",
        "Hank Doyle",
        "Hannah Smoterich-Barr",
        "Helene Beesly",
        "Hidetoshi Hasagawa",
        "Holly Flax",
        "Hunter Raymond",
        "Irene",
        "Isabel Poreba",
        "Ivan Shotsky",
        "Jack",
        "Jada Philbin",
        "Jake Palmer",
        "James P. Albini",
        "Jamie",
        "Jan Levinson",
        "Jasmine Windsong",
        "Jeb Schrute",
        "Jerry DiCanio",
        "Jesse Pinkman",
        "Jessica",
        "Jim Halpert",
        "Jo Bennett",
        "Jordan Garfield",
        "Julia",
        "Julie",
        "Julius Erving",
        "Justine Philbin",
        "Karen Filippelli",
        "Katy Moore",
        "Keith Bishop",
        "Kelly Kapoor",
        "Kendall",
        "Kenny Anderson",
        "Kevin Malone",
        "Kim Richy",
        "Konikotaka",
        "Laura Anderson",
        "Lee",
        "Leo",
        "Lester Schneider",
        "Lily",
        "Linda",
        "Lloyd Gross",
        "Lonny Collins",
        "Louanne Kelley",
        "Luke Cooper",
        "Lynn",
        "Madge Madsen",
        "Margaret",
        "Mark",
        "Mark Franks",
        "Martin Nash",
        "Marybeth",
        "Matt",
        "Maurie",
        "Megan"
    )

    val locations = listOf(
        "Poor Richard's Pub",
        "Schrute Farms",
        "Steamtown Mall",
        "Sandals Resort Jamaica",
        "Lake Wallenpaupack",
        "Cooper's Seafood",
        "The Warehouse",
        "Lackawanna Coal Mine",
        "Dwight's Gym for Muscles",
        "Prince Paper",
        "Scranton Business Park",
        "Vance Refrigeration",
        "Benihana",
        "The Bog",
        "Here Comes Treble",
    )

    val companies = listOf(
        // Paper Companies
        "Dunder Mifflin",
        "Sabre",
        "Prince Paper",
        "Michael Scott Paper Company",
        "Staples",
        "Office Depot",
        "Pendleton",
        // Major Competitors/Corporate
        "Staples",
        "Office Depot",
        "Big Red Paper Company",
        "Stone & Son Paper Company",
        // Dunder Mifflin Branches
        "Dunder Mifflin Scranton",
        "Dunder Mifflin Corporate",
        "Dunder Mifflin Stamford",
        "Dunder Mifflin Utica",
        "Dunder Mifflin Buffalo",
        "Dunder Mifflin Albany",
        "Dunder Mifflin Nashua",
        "Dunder Mifflin Camden",
        "Dunder Mifflin Yonkers",
        // Local Businesses
        "Poor Richard's Pub",
        "Chili's",
        "Hooters",
        "Cooper's Seafood",
        "Alfredo's Pizza Cafe",
        "Pizza by Alfredo",
        "Benihana",
        "Farley's Pub",
        // Client Companies
        "Blue Cross of Pennsylvania",
        "Harper Collins",
        "Pennsylvania Dutch Paper Company",
        "Stone & Son Paper Merchants",
        // Entertainment/Media
        "WBRE-TV News",
        "Scranton Times",
        "Sandals Resorts",
        "Here Comes Treble",
        // Small Businesses/Startups
        "Serenity by Jan",
        "Schrute Farms",
        "Athlead/Athleap",
        "Bob Vance Refrigeration",
        "Wuphf.com",
        "Shoe La La",
        "Mike's Cereal Shack",
        "The Faces of Scranton",
        "Somehow I Manage Publishing",
        // Real Estate
        "Vance Refrigeration",
        "Scranton Business Park",
        "Scranton Industrial Park",
        // Healthcare
        "Scranton Hospital",
        "Dr. Crentist's Dental Office",
        // Miscellaneous
        "Burlington Coat Factory",
        "Steamtown Mall",
        "Lackawanna County Coal Mine Tour",
        "Camp Wonetu",
        "Dwight Schrute Gym for Muscles",
        "Professor Copperfield's Miracle Legumes"
    )

}