package elias.fakerMaker.fakers.movies

object BackToTheFuture {
    val characters = listOf(
        "Happy-Feet Henderson",
        "Oddball Uncle Oliver",
        "Albert Einstein",
        "Alexander Graham Bell",
        "Andy Taylor",
        "Bifficus Antanneny",
        "Mr. Arky",
        "Arnie Benedict",
        "B.O. Beanes",
        "Babcock",
        "Babe Ruth",
        "Babs",
        "Ellen Baines",
        "Joey Baines",
        "Milton Baines",
        "Sally Baines",
        "Sam Baines",
        "Stella Baines",
        "Toby Baines",
        "Barack Obama",
        "Barney",
        "Battleship Potempkin",
        "Beatrice Spalding",
        "Myra Benson",
        "Bernie Kessoff",
        "Marlin Berry",
        "Marvin Berry",
        "Betty",
        "Betty Lapinski",
        "Betty Parker",
        "Bob Muglia",
        "Bobby",
        "John Wilkes Booth",
        "Bob Brothers",
        "Clara Clayton-Brown",
        "Emmett Brown",
        "Erhardt Brown",
        "Jules Brown",
        "Verne Brown",
        "Buck",
        "Bucktooth Langley",
        "George H. W. Bush",
        "Vannevar Bush",
        "Little Caesar",
        "Caligula",
        "Harry Callahan",
        "Al Capone",
        "Captain Hook",
        "Carl Sagan",
        "Carlton Ellsworth",
        "Lou Carruthers",
        "Jimmy Carter",
        "Ceegar",
        "Chad Stern",
        "Deborah Chambers",
        "King Charles II",
        "Charlie",
        "Checkerboard Charlie",
        "Chester",
        "Chester R. Brough",
        "Chris",
        "Chuck Berry",
        "Chuckles LeNart",
        "Clark Gable",
        "Daniel Clayton",
        "Martha Clayton",
        "Polly Clayton",
        "Ulysses S. Clayton",
        "Grover Cleveland",
        "Colin Clive",
        "Colonel Lomax",
        "Commissioner Wilson",
        "Milton Van Conrad III",
        "Calvin Coolidge",
        "Nicolaus Copernicus",
        "Michael Corleone",
        "Craig",
        "Davy Crockett",
        "Sonny Crockett",
        "John Crump",
        "Cue Ball",
        "Roland Culver",
        "Cynthia Solomon",
        "Cyrano de Bergerac",
        "D. Jones",
        "D.T. Broun",
        "Damian Kowal",
        "Dana Mitchell",
        "Thérèse de Dillmont",
        "Delores Miskin",
        "Queen Diana",
        "Charles Dickens",
        "Mark Dixon",
        "Dorothy",
        "Douglas H. Brown",
        "Jacques Douteux",
        "Dr. Seuss",
        "Durwood Bennington",
        "Clint Eastwood",
        "Thomas Edison",
        "Dwight D. Eisenhower",
        "Elmer Brown",
        "Engineer Dan",
        "Eratosthenes",
        "Ernest K. Brown",
        "Eunice",
        "Evan A. Brown",
        "Evan Russell",
        "Evelyn Dall",
        "Everett Pilson",
        "Eyepatch",
        "Frank Fargo",
        "Fedgewick",
        "Mr. Figgins",
        "Foley",
        "Benjamin Franklin",
        "Fred",
        "Ito T. Fujitsu",
        "Gabriela Sanchez",
        "M.R. Gale",
        "Galileo Galilei",
        "Genevieve Parker",
        "George Moon",
        "Gerald Ford",
        "Gigawatt",
        "Glenann Godden",
        "Mrs. Gomez",
        "Dexter Gore",
        "Ulysses S. Grant",
        "Greg",
        "Lev Grossman",
        "Leslie Groves",
        "H.G. Wells",
        "H.W. Broomhead",
        "George Ellery Hale",
        "Fawn Hall",
        "Hampton",
        "Hans Peterson",
        "Harold Lloyd",
        "Harpo Marx",
        "Heather",
        "Herbert Hoover",
        "Howard",
        "Hubert",
        "Huey Lewis",
        "Hyrum C. Brough",
        "J. J. Valenti",
        "J. Williams",
        "Jack Benny",
        "Jackie Gleason",
        "Jackson",
        "Michael Jackson",
        "Jayne Mansfield",
        "Jeb",
        "Jessica Hahn",
        "Jesus Christ",
        "Jim Decker",
        "Jim McFly",
        "Jimmy",
        "Jimmy Joe Statler",
        "Joey",
        "Johann",
        "John"
    )

    val companies = listOf(
        "Biff's Pleasure Paradise",
        "Hill Valley Railroad Station",
        "Pohatchee Drive-In",
        "Boot Hill Cemetery",
        "Clayton Ravine",
        "Delgado Mine",
        "Hilldale",
        "Palace Saloon",
        "Lou's Cafe",
        "Lou's Aerobic Fitness Center",
        "Cafe 80's",
        "McFly Residence",
        "Tannen's Residence",
        "Blast from the Past",
        "Hill Valley Telegraph Office",
        "Statler Toyota",
        "Statler Pontiac",
        "Oak Park Cemetery",
        "River Road Tunnel",
        "Riverside Drive"
    )
}