package elias.fakerMaker.fakers.movies

object StarWars {
    val characters = listOf(
        // Original Trilogy Main Characters
        "Luke Skywalker",
        "Leia Organa",
        "Han Solo",
        "Chewbacca",
        "Darth Vader",
        "Obi-Wan Kenobi",
        "Yoda",
        "C-3PO",
        "R2-D2",
        "Emperor Palpatine",
        "Lando Calrissian",
        "Boba Fett",
        "Jabba the Hutt",
        "Admiral Ackbar",
        "Mon Mothma",
        "Wedge Antilles",
        "General Veers",
        "Admiral Piett",
        // Original Trilogy Supporting Characters
        "Greedo",
        "Biggs Darklighter",
        "General Dodonna",
        "Nien Nunb",
        "Lobot",
        "General Rieekan",
        "Commander Needa",
        "Captain Needa",
        "Admiral Ozzel",
        "Dak Ralter",
        "General Madine",
        "Wicket W. Warrick",
        "Chief Chirpa",
        "Logray",
        "Bib Fortuna",
        "Salacious B. Crumb",
        "Max Rebo",
        "Sy Snootles",
        "EV-9D9",
        "Malakili",
        "Oola",
        "Bossk",
        "IG-88",
        "Dengar",
        "4-LOM",
        "Zuckuss",
        "Admiral Motti",
        "General Tagge",
        "Grand Moff Tarkin",
        // Prequel Trilogy Main Characters
        "Anakin Skywalker",
        "Padmé Amidala",
        "Qui-Gon Jinn",
        "Mace Windu",
        "Count Dooku",
        "Jango Fett",
        "Shmi Skywalker",
        "Jar Jar Binks",
        "Captain Panaka",
        "Nute Gunray",
        "General Grievous",
        "Commander Cody",
        "Captain Rex",
        "Bail Organa",
        "Captain Typho",
        "Watto",
        "Sebulba",
        // Prequel Trilogy Supporting Characters
        "Dexter Jettster",
        "Zam Wesell",
        "Cliegg Lars",
        "Owen Lars",
        "Beru Lars",
        "Dormé",
        "Sabé",
        "Cordé",
        "Mas Amedda",
        "Sio Bibble",
        "Boss Nass",
        "Captain Tarpals",
        "Rune Haako",
        "San Hill",
        "Poggle the Lesser",
        "Wat Tambor",
        "Sly Moore",
        "Jocasta Nu",
        "Coleman Trebor",
        "Even Piell",
        "Saesee Tiin",
        "Yarael Poof",
        "Oppo Rancisis",
        "Adi Gallia",
        "Stass Allie",
        "Eeth Koth",
        "Agen Kolar",
        "Depa Billaba",
        // Clone Wars Era Characters
        "Ahsoka Tano",
        "Asajj Ventress",
        "Savage Opress",
        "Pre Vizsla",
        "Satine Kryze",
        "Bo-Katan Kryze",
        "Cad Bane",
        "Hondo Ohnaka",
        "Barriss Offee",
        "Mother Talzin",
        "Saw Gerrera",
        "Admiral Trench",
        "Plo Koon",
        "Kit Fisto",
        "Shaak Ti",
        "Aayla Secura",
        "Ki-Adi-Mundi",
        // Clone Wars Supporting Characters
        "Commander Wolffe",
        "Commander Fox",
        "Commander Gree",
        "Commander Bly",
        "Commander Bacara",
        "99",
        "Cut Lawquane",
        "Hardcase",
        "Fives",
        "Echo",
        "Hevy",
        "Jesse",
        "Kix",
        "Dogma",
        "Tup",
        "Waxer",
        "Boil",
        "Embo",
        "Sugi",
        "Latts Razzi",
        "Rush Clovis",
        "Lux Bonteri",
        "Steela Gerrera",
        "Pre Vizsla",
        "Gar Saxon",
        "Rook Kast",
        "Ursa Wren",
        "Almec",
        // Sequel Trilogy Characters
        "Rey Skywalker",
        "Finn",
        "Poe Dameron",
        "Kylo Ren",
        "Supreme Leader Snoke",
        "General Hux",
        "Rose Tico",
        "BB-8",
        "Maz Kanata",
        "Captain Phasma",
        "General Pryde",
        "Babu Frik",
        "Zorii Bliss",
        "DJ",
        "Lieutenant Connix",
        "Snap Wexley",
        // Sequel Trilogy Supporting Characters
        "Lor San Tekka",
        "Unkar Plutt",
        "Admiral Holdo",
        "Paige Tico",
        "Lieutenant Mitaka",
        "Colonel Datoo",
        "Captain Canady",
        "Commander D'Acy",
        "Beaumont Kin",
        "Jannah",
        "Klaud",
        "R2-KT",
        "Boolio",
        "Aftab Ackbar",
        "Dominic Monaghan's Character",
        "Snap Wexley",
        "Tallie Lintra",
        "C'ai Threnalli",
        // Mandalorian Era Characters
        "Din Djarin",
        "Grogu",
        "Cara Dune",
        "Greef Karga",
        "Kuiil",
        "IG-11",
        "The Client",
        "Fennec Shand",
        "Moff Gideon",
        "The Armorer",
        "Paz Vizsla",
        "Peli Motto",
        "Cobb Vanth",
        "Morgan Elsbeth",
        // Mandalorian Supporting Characters,
        "Omera",
        "Winta",
        "The Mythrol",
        "Toro Calican",
        "Xi'an",
        "Qin",
        "Ranzar Malk",
        "Burg",
        "Zero",
        "Dr. Pershing",
        "Lang",
        "Riot Mar",
        "Davan",
        "The Frog Lady",
        "Axe Woves",
        "Koska Reeves",
        // Rogue One Characters
        "Jyn Erso",
        "Cassian Andor",
        "K-2SO",
        "Chirrut Îmwe",
        "Baze Malbus",
        "Bodhi Rook",
        "Orson Krennic",
        "Galen Erso",
        "Saw Gerrera",
        "Mon Mothma",
        // Rogue One Supporting Characters
        "Lyra Erso",
        "Tivik",
        "Blue Squadron Leader",
        "Red Squadron Leader",
        "Gold Squadron Leader",
        "General Draven",
        "Senator Jebel",
        "Senator Pamlo",
        "General Merrick",
        "Admiral Raddus",
        "Corporal Tonc",
        "Lieutenant Sefla",
        "Pao",
        "Bistan",
        // Solo Characters
        "Young Han Solo",
        "Qi'ra",
        "Tobias Beckett",
        "L3-37",
        "Dryden Vos",
        "Val",
        "Rio Durant",
        "Enfys Nest",
        // Solo Supporting Characters
        "Lady Proxima",
        "Moloch",
        "Rebolt",
        "Imperial Recruitment Officer",
        "Weazel",
        "Aemon Gremm",
        "Imperial Mudtrooper",
        "Ralakili",
        "Tak",
        "Syke",
        // Other Notable Characters
        "Grand Admiral Thrawn",
        "Doctor Aphra",
        "Black Krrsantan",
        "Quinlan Vos",
        "Durge",
        "Kyle Katarn",
        "Mara Jade",
        "Grand Inquisitor",
        "Fifth Brother",
        "Seventh Sister",
        "Second Sister",
        "Ninth Sister",
        "Starkiller",
        "Darth Revan",
        "Darth Malak",
        "HK-47",
        "Bastila Shan",
        // Extended Universe/Legends Characters
        "Jacen Solo",
        "Jaina Solo",
        "Anakin Solo",
        "Ben Skywalker",
        "Talon Karrde",
        "Grand Admiral Pellaeon",
        "Corran Horn",
        "Dash Rendar",
        "Prince Xizor",
        "Nom Anor",
        "Exar Kun",
        "Ulic Qel-Droma",
        "Nomi Sunrider",
        // Extended Universe/Legends Supporting Characters
        "Joruus C'baoth",
        "Borsk Fey'lya",
        "Winter Celchu",
        "Tycho Celchu",
        "Wedge Antilles",
        "Wes Janson",
        "Derek 'Hobbie' Klivian",
        "Gavin Darklighter",
        "Mirax Terrik",
        "Booster Terrik",
        "Kam Solusar",
        "Tionne Solusar",
        "Kir Kanos",
        "Carnor Jax",
        "Admiral Daala",
        "Kyp Durron",
        "Callista Ming"
    )

    val companies = listOf(
        // Galactic Governments and Administration
        "Galactic Republic",
        "Galactic Empire",
        "First Order",
        "New Republic",
        "Confederacy of Independent Systems",
        "Trade Federation",
        "Galactic Senate",
        "Imperial Senate",
        "Republic Judiciary",
        "Imperial Security Bureau",
        "Republic Treasury",
        "Imperial Office of Criminal Investigations",
        "Bureau of Ships and Services",
        "Imperial Diplomatic Corps",
        "Republic Diplomatic Corps",
        "Imperial Department of Military Research",
        "Commission for the Preservation of the New Order",

        // Criminal Organizations and Syndicates
        "Hutt Cartel",
        "Black Sun",
        "Crimson Dawn",
        "Pike Syndicate",
        "Shadow Collective",
        "Pyke Syndicate",
        "Crymorah Syndicate",
        "Exchange",
        "Zann Consortium",
        "Ohnaka Gang",
        "Guavian Death Gang",
        "Kanjiklub",
        "Droid Gotra",
        "Hutts' Council",
        "Car'das Smugglers",
        "Klatooinian Trade Guild",

        // Major Corporations
        "Banking Clan",
        "Techno Union",
        "Commerce Guild",
        "Kuat Drive Yards",
        "Czerka Corporation",
        "Incom Corporation",
        "Sienar Fleet Systems",
        "Corporate Sector Authority",
        "BlasTech Industries",
        "Corellian Engineering Corporation",
        "Rendili StarDrive",
        "TaggeCo",
        "SoroSuub Corporation",
        "Industrial Automaton",
        "Merr-Sonn Munitions",
        "Mon Calamari Shipyards",
        "Arakyd Industries",
        "MandalMotors",
        "Koensayr Manufacturing",
        "Cybot Galactica",
        "Baktoid Armor Workshop",
        "Core Galaxy Systems",
        "Corellian Mining Corporation",
        "Hoersch-Kessel Drive",
        "Kuat Systems Engineering",
        "Lothial Shipping",
        "Neuro-Saav Corporation",
        "Novaldex",
        "Quadex Corporation",
        "Republic Sienar Systems",
        "Roche Hive",
        "Santhe Corporation",
        "Slayn & Korpil",
        "Subpro Corporation",
        "Tendrando Arms",
        "TransGalMeg Industries",
        "Ubrikkian Industries",
        "Veril Line Systems",
        "Vaufthau Processing Industries",

        // Educational and Research Institutions
        "Coruscant Planetary University",
        "Imperial Academy",
        "Republic Academy",
        "Carida Academy",
        "Corulag Academy",
        "Prefsbelt Fleet Camp",
        "Skystrike Academy",
        "Royal Academy of Government",
        "Arkanis Academy",
        "Hosnian Prime Academy",
        "Coronet City University",
        "Coruscant Medical School",
        "Rhinnal State Medical Academy",
        "University of Bar'leth",
        "University of Rudrig",
        "Theed Royal Academy",
        "Coruscant Institute of Technology",
        "Republic Institute of Technology",
        "Imperial Engineering Academy",

        // Planetary Governments
        "Naboo Royal Government",
        "Alderaan Royal Family",
        "Mon Cala Council",
        "Mandalorian Government",
        "Coruscant Planetary Defense",
        "Cloud City Administration",
        "Onderon Royal Court",
        "Hapes Consortium",
        "Bothan Council",
        "Chandrila State Government",
        "Corellia Planetary Government",
        "Fondor Planetary Government",
        "Kuat Planetary Government",
        "Malastare Planetary Government",
        "Ryloth Resistance",
        "Sullust Planetary Government",
        "Taris Planetary Council",

        // Commercial Establishments
        "Canto Bight Casino",
        "Bespin Mining Corporation",
        "Coronet City Shipyards",
        "Coruscant Merchants' Guild",
        "Kessel Mining Corporation",
        "Tibanna Gas Mining Guild",
        "Corellia Mining Corporation",
        "Mygeeto Banking Clan",
        "Fondor Shipyards",
        "Corellia Tourist Bureau",
        "Coruscant Tourism Board",
        "Naboo Tourist Center",
        "Bespin Tourist Authority",

        // Major Organizations
        "Jedi Order",
        "Jedi Service Corps",
        "Jedi Temple",
        "Bounty Hunters' Guild",
        "Mining Guild",
        "Smugglers' Alliance",
        "Order of the Sith Lords",
        "ExGal Society",
        "Antarian Rangers",
        "Church of the Force",
        "Imperial Knights",
        "Jedi Agricultural Corps",
        "Jedi Educational Corps",
        "Jedi Exploration Corps",
        "Jedi Medical Corps",

        // Media and Information
        "HoloNet News",
        "Imperial HoloVision",
        "Galaxy News Service",
        "Imperial Press Corps",
        "Coruscant Daily NewsFeed",
        "Core Worlds Holofeed",
        "Republic HoloNews",
        "Outer Rim News Network",
        "Chandrila Broadcasting Corporation",
        "Corellian Broadcasting Corporation",

        // Transportation and Infrastructure
        "Coruscant Transport Authority",
        "Imperial Department of Transit",
        "Republic Transit Authority",
        "Galactic Transportation System",
        "Coruscant Port Authority",
        "Kuat Passenger Service",
        "Corellian Transit Authority",
        "Republic Hyperspace Routes Authority",
        "Imperial Navigation Bureau",

        // Healthcare
        "Republic Medical Institute",
        "Imperial Medical Corps",
        "Coruscant General Hospital",
        "Rhinnal State Medical Academy",
        "Alderaan Medical Institute",
        "Coruscant Health Service",
        "Republic Health Ministry",
        "Imperial Health Organization",
        "Naboo Royal Medical Service",

        // Financial Institutions
        "Bank of the Core",
        "Galactic Banking Authority",
        "Muunilinst Banking Clan",
        "Commerce Bank of Correllia",
        "First Bank of Aargau",
        "Scipio Banking Clan",
        "Bank of the Republic",
        "Coruscant Banking Institute",
        "Imperial Treasury",

        // Professional Organizations
        "Coruscant Bar Association",
        "Galactic Engineers Union",
        "Spacers' Guild",
        "Republic Engineers' Corps",
        "Coruscant Legal Society",
        "Imperial Bar Association",
        "Architects Guild",
        "Coruscant Medical Board",
        "Pilots Guild",
        "Mechanics Guild",
        "Traders Guild",
        "Merchants' Protective Association"
    )
}