package elias.fakerMaker.fakers

object KingOfTheHill {

    val characters = listOf(
        "Abbie",
        "Abbie Holiday",
        "Ace",
        "Acne Pete",
        "Adrian Young",
        "Akihito",
        "Alabaster Jones",
        "Alex",
        "Alexi Golgarin",
        "Alexis",
        "Alice",
        "Alison",
        "Alla Lubecki",
        "Ally",
        "Alphonse Dauterive",
        "Amanda",
        "Amy",
        "Amy Edlin",
        "Amy Pitman",
        "Andy Maynard",
        "Angela",
        "Ani DiFranco",
        "Ann Richards",
        "Anne",
        "Anthony",
        "Anthony Page",
        "Antonio Felipe",
        "Appleseed",
        "April",
        "Asa",
        "Ashley Rae",
        "Assistant Pastor Larry",
        "Audrey",
        "Bandit",
        "Barks",
        "Barry",
        "Barry Rollins",
        "Bear",
        "Becky",
        "Beef",
        "Benson",
        "Bert Halverstrom",
        "Bethany",
        "Betty",
        "Big Jim",
        "Bill Dauterive",
        "Billy F. Gibbons",
        "Billy Ray Walters",
        "Bitsy",
        "Blanca",
        "Blanche",
        "Bloomers",
        "Bob",
        "Bob Choate",
        "Bob Handley",
        "Bob Jenkins",
        "Bobby Hill",
        "Bodhi",
        "Bonnie",
        "Bora",
        "Boris",
        "Boyce Hubert",
        "Brad",
        "Bradley",
        "Brandon",
        "Brent Steel",
        "Bret Winslow",
        "Britney Spears",
        "Brock",
        "Brooklyn",
        "Bruce Tuttle",
        "Bruce Willis",
        "Bryce Carmody",
        "Bubba",
        "Buck Strickland",
        "Buckley",
        "Bud Ferguson",
        "Buddy",
        "Buddy Ebsen",
        "Bug Gribble",
        "Bunny Hicks",
        "Burl Arlington",
        "Burnett Cobb",
        "Burt Burton",
        "Buttercup McGee",
        "C. Everett Koop",
        "C.J.",
        "Caleb",
        "Candee Lace",
        "Candi",
        "Candy",
        "Cane Skretteburg",
        "Captain Hart",
        "Carl",
        "Carl Moss",
        "Carla",
        "Carly",
        "Carolyn",
        "Catcher",
        "Catherine Zeta-Jones",
        "Cathy Shears",
        "Celery Head",
        "Chairman Geiger",
        "Chane Wassanasong",
        "Chappy",
        "Charlene",
        "Charlie",
        "Charlie Daniels",
        "Charlie Fortner",
        "Charlie St. Clair",
        "Charlton Heston",
        "Chester",
        "Chet",
        "Chet Elderson",
        "Chet Haddock",
        "Chet Halley",
        "Chiffon",
        "Chip Block",
        "Chris Kirkpatrick",
        "Chris Sizemore",
        "Christina Aguilera",
        "Chuck Garrison",
        "Chuck Mangione",
        "Cindi",
        "Cindy Wassanasong",
        "Cissy Cobb",
        "Claire",
        "Clark Peters",
        "Claude Stokes",
        "Claudia",
        "Clay Henry",
        "Cleo",
        "Clint Black",
        "Coach Bradford",
        "Coach Kleehammer",
        "Coach Maxwell",
        "Coach Palmer",
        "Coach Sauers",
        "Cole Kitten",
        "Coleman Lucas",
        "Colette Davis",
        "Commissioner Evers",
        "Conductor Nolan",
        "Connie Souphanousinphone",
        "Conrad Meinhofer IV",
        "Cotton Hill"
    )

    val company = listOf(
        "1st & Ten Sports Memorabilia",
        "1st Texas Bank",
        "24-Hour Computer Heaven",
        "4Skore",
        "A Better You",
        "AAA",
        "ABC Insulation Corporation",
        "Agora Theater",
        "Al's Hunting Supply",
        "Alamo Beer Brewing Co.",
        "Alamo Land",
        "Alamo Liquor",
        "All Creatures Big & Small Pet Boarding",
        "All the Queen's Men",
        "Antique Shoppe",
        "Arlen Animal Shelter",
        "Arlen Auto Club",
        "Arlen Auto Parts",
        "Arlen Bank & Trust",
        "Arlen Bowl",
        "Arlen Bus Depot",
        "Arlen Florist",
        "Arlen Fun Center",
        "Arlen Mall",
        "Arlen Medical Plaza",
        "Arlen Snake Farm and Boot Outlet",
        "Arlen Speedway",
        "Arlen State Psychiatric Hospital",
        "Arlen Theater",
        "Arlen VFW",
        "Arlen Video",
        "Arlen Vision Center",
        "Arlen YMCA",
        "Arlen's Jeans West",
        "Army Surplus",
        "Austinental Hotel",
        "Bibs & Cribs",
        "Big and Tall Women's Shoes and Socks",
        "Big Jim's Giant Screen Super Circus",
        "Big Mountain Fudgecake",
        "Big Water",
        "Body Buddy Health Club",
        "Bookies Readin Room",
        "Boremans' Books",
        "Branson Bus Depot",
        "Branson Theatre",
        "Bridal Path Wedding Boutique",
        "Burton's Corporate Headquarters",
        "Button Gwinnett Insurance",
        "Casa Linda",
        "CD Warehouse",
        "Channel 84",
        "Cheapskates",
        "Chimney Pipe Bar & Social Club",
        "Clarissa's Closet",
        "Clark Mobile Homes",
        "Comforting Pines Mental Health Center",
        "Complete Nutrition",
        "CornuCO-OPia",
        "Cover to Cover Books",
        "Dale's Dead-Bug",
        "Dark Star",
        "Dearborn",
        "Deluxe Tux",
        "Denton Flea Market",
        "Dermie's",
        "Double Eagle",
        "Dr. Stephens Cosmetic Dermatology",
        "Dr. Yandell's Veterinary Office",
        "DRCY",
        "Durndell County Speedway",
        "Durndle Bar",
        "Durndle Meats",
        "Durndle Savings",
        "Earl's Music Shop",
        "Econo-Suites",
        "El Grande Vista",
        "El Mercado",
        "Emerson Hardware",
        "Farmer's Market",
        "Foto Phast",
        "Futura Hotel",
        "Get In Get Out",
        "Gnome on the Range",
        "H. Dumpty's",
        "Handley Brothers Automotive Repair",
        "Hardware Ranch",
        "Harmonaholics",
        "Heimlich 18",
        "Heimlich County Zoo",
        "Heimlich Savings",
        "Hobby Odyssey",
        "Hooked on a Feline",
        "Hotel Arlen",
        "Hotel Arlington",
        "Hotel Toyko",
        "Hottyz",
        "House Gifts",
        "Hudspeth Drive-In",
        "J&J's Propane",
        "J.R.R. Tokens",
        "Jolly Roger Motel",
        "Jugstore Cowboys",
        "Kopy Kingdom",
        "Kris' Kopy Shop",
        "La Grunta Hotel",
        "Lake Arlen Rentals",
        "Lane Pratley Cadillac Hyundai",
        "Lawn Store and the Garden Shoppe",
        "Layaway Ray's Bait N' Tackle",
        "Liquor Trunk",
        "Lone Star Home and Casualty",
        "Lonestar Gay Rodeo Association",
        "Lubbocks Very Big Shoes",
        "Ma and Pa General Store",
        "Manitoba Tobacco Corporation",
        "Marty O's",
        "McMaynerbury Hilton",
        "McMaynerbury Hotel",
        "Mega Lo Mart",
        "MetaLife International",
        "Metrowalk",
        "Mike & Caroline's Roadside Inn",
        "MK's",
        "Motel Arlen",
        "Mr. Li's Moxibustion Clinic",
        "Nifty Grifty's Truckstop",
        "Night Bar",
        "Nine Rivers Country Club",
        "Omega House",
        "Paige Turner's Books",
        "Passages Health Food Market",
        "Patterson's Appliances and More",
        "Peggy's World of Books",
        "Pick-Up Truck Heaven",
        "Pink & White",
        "Portraits by Ron",
        "Primary Edge",
        "Pro AM Sports",
        "Randy's Hobby Shop",
        "Red Carpet Video",
        "Renovation Hardware",
        "Rhinestein's Cowboy",
        "Rutkowski Septic",
        "Sensei Ed's Karate Studio",
        "Seranie's Beauty Supply",
        "Shalackers",
        "Shelwyn's",
        "Shops at the Arboretum",
        "Six Malls Over Texas",
        "Sizemore Realty",
        "Sobin Medical Supply",
        "Sonny's Towing",
        "Soy To The World",
        "Speakerz Music",
        "Sporting Goods",
        "Stems and Seeds",
        "Strickland East",
        "Strickland North",
        "Strickland Propane",
        "Strickland South",
        "Strickland West",
        "Sue's Truck Motel",
        "Tea & Texas Toast",
        "Techno Pure, Inc.",
        "Thatherton Fuels",
        "The 5747 Club",
        "The Colton Gallery",
        "The Life Boat",
        "The Point After Lounge",
        "The Wichitan",
        "Tom Hammond World of Cars",
        "Transnational Amusements Studios",
        "Treble Clef Music Co.",
        "TV & VCR Repair",
        "Ugly's Saloon",
        "United Dairy Milk Conglomerate",
        "Vet Consortium",
        "Washer World",
        "West Arlen Medical Center",
        "Y'all Store-It",
        "Yoga Spot"
    )

    val locations = listOf(
        "1st & Ten Sports Memorabilia",
        "1st Texas Bank",
        "24-Hour Computer Heaven",
        "A Better You",
        "AAA",
        "ABC Insulation Corporation",
        "Abracapasta",
        "Agora Theater",
        "Al's Diner",
        "Al's Hunting Supply",
        "Alamo Beer Brewing Co.",
        "Alamo Land",
        "Alamo Liquor",
        "All Creatures Big & Small Pet Boarding",
        "All the Queen's Men",
        "Alley",
        "American Consulate",
        "Antique Shoppe",
        "Arlen",
        "Arlen Animal Shelter",
        "Arlen Auto Club",
        "Arlen Auto Parts",
        "Arlen Bank & Trust",
        "Arlen Beauty Academy",
        "Arlen Bowl",
        "Arlen Bus Depot",
        "Arlen Bystander",
        "Arlen City Hall",
        "Arlen City Public Park",
        "Arlen Community Center",
        "Arlen Community College",
        "Arlen Convention Center",
        "Arlen County Child Protective Services",
        "Arlen County Courthouse",
        "Arlen District Office",
        "Arlen Financial Services",
        "Arlen Fire Department",
        "Arlen First Methodist Church",
        "Arlen Florist",
        "Arlen Fun Center",
        "Arlen Gun Club",
        "Arlen Heights",
        "Arlen High School",
        "Arlen Mall",
        "Arlen Medical Associates",
        "Arlen Medical Plaza",
        "Arlen Municipal Garbage Dump",
        "Arlen Museum",
        "Arlen Nursery",
        "Arlen Pet Depot",
        "Arlen Police Station",
        "Arlen Post Office",
        "Arlen Public Golf Course",
        "Arlen Public Library",
        "Arlen Salvage",
        "Arlen Snake Farm and Boot Outlet",
        "Arlen Speedway",
        "Arlen State Psychiatric Hospital",
        "Arlen Theater",
        "Arlen Town Hall",
        "Arlen Train Station",
        "Arlen VFW",
        "Arlen Video",
        "Arlen Vision Center",
        "Arlen Water Tower",
        "Arlen YMCA",
        "Arlen's Jeans West",
        "Arlen's Magic Pan",
        "Arlen-McMaynerbury Regional Medical Center",
        "Army Surplus",
        "Attaché",
        "Austinental Hotel",
        "Bacon 'N Waffles",
        "Barbara's Diner",
        "Bat Bridge",
        "Bazooms!",
        "Belcher's Grove",
        "Belton Middle School",
        "Bibs & Cribs",
        "Big and Tall Women's Shoes and Socks",
        "Big Jim's Giant Screen Super Circus",
        "Big Water",
        "Billy Sundae's Old Time Creamery",
        "Blue Bonnet Creamery",
        "Body Buddy Health Club",
        "Bookies Readin Room",
        "Boremans' Books",
        "Branson",
        "Branson Bus Depot",
        "Branson Theatre",
        "Bridal Path Wedding Boutique",
        "Bull's Eye Shooting Range",
        "Burton's Corporate Headquarters",
        "Burton's Prime Rib",
        "Button Gwinnett Insurance",
        "C.O.S. Communication Outsource Solutions",
        "Captain Bear's Pizza",
        "Casa Linda",
        "Catfish Plantation",
        "CD Warehouse",
        "Chainsaw",
        "Channel 84",
        "Cheapskates",
        "Cheese 'N' Fries Super Star",
        "Chimney Pipe Bar & Social Club",
        "Chops Steakhouse",
        "Clarissa's Closet",
        "Clark Mobile Homes",
        "Coburn Fairgrounds",
        "Coffee Break",
        "Comforting Pines Mental Health Center",
        "Complete Nutrition",
        "Cooligan's",
        "CornuCO-OPia",
        "Corpus Christi",
        "County Administration Building",
        "County Animal Control",
        "County Gun Club",
        "Cover to Cover Books",
        "Dairy Queen",
        "Dallas",
        "Dallas Grand Plaza",
        "Dallas Museum of Modern Art",
        "Dark Star",
        "Dearborn",
        "Deluxe Tux",
        "Denton",
        "Denton Flea Market",
        "Department of Motor Vehicles",
        "Department of Public Safety",
        "Dermie's",
        "Double Eagle",
        "Dr. Stephens Cosmetic Dermatology",
        "Dr. Yandell's Veterinary Office",
        "DRCY",
        "Durndell",
        "Durndell County",
        "Durndell County Speedway",
        "Durndle Bar",
        "Durndle Meats",
        "Durndle Savings",
        "Earl's Music Shop",
        "East Bridge Service Entrance",
        "Econo-Suites",
        "El Grande Vista",
        "El Mercado",
        "El Shrimp Bucket",
        "Elks Lodge no. 23",
        "Emerson Hardware",
        "Everwood Country Club",
        "Farmer's Market",
        "Federal Courthouse",
        "Fort Berk",
        "Fort Blanda Army Base",
        "Foto Phast",
        "Frozen Cow Creamery",
        "Futura Hotel",
        "Garrity & Sons Nursing Home",
        "Get In Get Out",
        "Gnome on the Range",
        "Goobersmooches",
        "H. Dumpty's",
        "Handley Brothers Automotive Repair",
        "Hardware Ranch",
        "Heimlich 18",
        "Heimlich County",
        "Heimlich County Airport",
        "Heimlich County Courthouse",
        "Heimlich County Fair",
        "Heimlich County Medical Center",
        "Heimlich County Museum of Natural History",
        "Heimlich County Physical Therapy",
        "Heimlich County Rodeo",
        "Heimlich County Sheriff's Station",
        "Heimlich County Sports Medical Center",
        "Heimlich County Zoo",
        "Heimlich Savings",
        "Hobby Odyssey",
        "Holly Springs Retirement Village",
        "Hooked on a Feline",
        "Hotel Arlen",
        "Hotel Arlington",
        "Hotel Toyko",
        "Hottyz",
        "House Gifts",
        "Houston",
        "Houston Hospital",
        "Hudspeth Drive-In",
        "J&J's Propane",
        "J.R.R. Tokens",
        "John Redcorn's trailer",
        "John Wayne State Park",
        "Jolly Roger Motel",
        "Jugstore Cowboys"
    )

}