package elias.fakerMaker.fakers

object ThroneOfGlass {
    val characters = listOf(
        "Abraxos",
        "Aedion Ashryver",
        "Aelin Galathynius",
        "Aghrun",
        "Amithy",
        "Anneith",
        "Ansel of Briarcliff",
        "Archer Finn",
        "Arghun",
        "Arobynn Hamel",
        "Asterin Blackbeak",
        "Asterion",
        "Athril",
        "Baba Yellowlegs",
        "Ben",
        "Benson",
        "Benzo Doneval",
        "Bill Chastain",
        "Blackbeak Matron",
        "Borte",
        "Brannon Galathynius",
        "Briar Blackbeak",
        "Bronwen Vanora",
        "Cain",
        "Cairn",
        "Cal Lochan",
        "Chaol Westfall",
        "Cindrillion Ashryver",
        "Clarisse DuVency",
        "Connall",
        "Cormac",
        "Cresseida Blueblood",
        "Cyrene",
        "Deanna",
        "Delara Faliq",
        "Dorian Havilliard",
        "Dorian Havilliard I",
        "Dresenda",
        "Duke Perrington",
        "Duva",
        "Edda Blackbeak",
        "Elena Galathynius Havilliard",
        "Elgan",
        "Elide Lochan",
        "Elise",
        "Ellys Whitethorn",
        "Emrys",
        "Endymion Whitethorn",
        "Erawan",
        "Eretia",
        "Essar",
        "Evalin Galathynius",
        "Evangeline",
        "Faline Blackbeak",
        "Falkan Ennar",
        "Fallon Blackbeak",
        "Farasha",
        "Farnor",
        "Fendir",
        "Fenrys Moonbeam",
        "Finnula",
        "Fleetfoot",
        "Gabriella",
        "Galan Ashryver",
        "Gavin Havilliard",
        "Gavriel",
        "Georgina Havilliard",
        "Ghislaine Blackbeak",
        "Glaston Ashryver",
        "Glennis Crochan",
        "Grand Empress",
        "Grave",
        "Gregori",
        "Hafiza",
        "Harding",
        "Hasar",
        "Hellas",
        "Hollin Havilliard",
        "Houlun",
        "Ilias",
        "Imogen Blackbeak",
        "Ioan Jayne",
        "Iskra Yellowlegs",
        "Josefin Towers",
        "Kadara",
        "Kadja",
        "Kaltain Rompier",
        "Kashin",
        "Kaya Blackbeak",
        "Keelie",
        "Keva",
        "Kharankui",
        "Kyllian",
        "Lady of the Great Deep",
        "Lani",
        "Lidia Cervos",
        "Linnea Blackbeak",
        "Lithaen",
        "Lorcan Salvaterre",
        "Lord Berick",
        "Lord Nirall",
        "Lord Westfall",
        "Lothian Blackbeak",
        "Luca",
        "Lumas",
        "Lyria",
        "Lysandra",
        "Mab",
        "Madam Florine",
        "Maddy",
        "Maeve",
        "Mala Fire-Bringer",
        "Malakai",
        "Manon Blackbeak",
        "Mantyx",
        "Marion Lochan",
        "Mikhail",
        "Molly",
        "Mora",
        "Mort",
        "Ms. Cortland",
        "Mullin",
        "Murtaugh Allsbrook",
        "Narene",
        "Narrok",
        "Ned Clement",
        "Nehemia Ytger",
        "Nelly",
        "Nesryn Faliq",
        "Nolan",
        "Nox Owen",
        "Olgnia Towers",
        "Ombriel",
        "Orcus",
        "Orda",
        "Orlon Galathynius",
        "Petrah Blueblood",
        "Philippa Spindlehead",
        "Pytor",
        "Remelle",
        "Ren Allsbrook",
        "Rena Goldsmith",
        "Renia",
        "Ress",
        "Rhiannon Crochan",
        "Rhiannon Crochan II",
        "Rhoe Galathynius",
        "Ridderak",
        "Roland Havilliard",
        "Rolfe",
        "Rosamund",
        "Rose Allsbrook",
        "Rourke Farran",
        "Rowan Whitethorn",
        "Sam Cortland",
        "Sartaq",
        "Sayed Faliq",
        "Sellene Whitethorn",
        "Shen",
        "Silba",
        "Sorrel Blackbeak",
        "Sorscha",
        "Stevan",
        "Taratjah",
        "Temis",
        "Tern",
        "Terrin Westfall",
        "The Hunter",
        "The Lord of the North",
        "The Mute Master",
        "The Sin-Eater",
        "Thea Blackbeak",
        "Theodus Brullo",
        "Three-Faced Goddess",
        "Titus",
        "Tristan Crochan",
        "Tumelun",
        "Urus",
        "Vaughan",
        "Vernon Lochan",
        "Vesta Blackbeak",
        "Wesley",
        "Weylan Darrow",
        "Xavier Forul",
        "Yellowlegs Matron",
        "Yeran"
    )

    val locations = listOf(
        "Adarlan",
        "Amaroth",
        "Anielle",
        "Antica",
        "Assassin's Keep",
        "Bellhaven",
        "Calaculla",
        "Caraverre",
        "Doranelle",
        "Eastern Continent",
        "Endovier",
        "Erilea",
        "Eyllwe",
        "Fenharrow",
        "Ferian Gap",
        "Glass Castle",
        "Ilium",
        "Innish",
        "Marte Towers",
        "Meah",
        "Melisande",
        "Mistward",
        "Morath",
        "Noll",
        "Oakwald Forest",
        "Orynth",
        "Perranth",
        "Rifthold",
        "Ruhnn Mountains",
        "Skull's Bay",
        "Southern Continent",
        "Tavan Mountains",
        "Terrasen",
        "The Glass Palace",
        "The Realm of the Valg",
        "The Red Desert",
        "The Silver Lake",
        "The Vaults",
        "The Womb",
        "Torre Cesme",
        "Varese",
        "Wendlyn",
        "White Fang Mountains",
        "Witch Kingdom"
    )
}