package elias.fakerMaker.fakers.tvshow

object GravityFalls {
    val characters = listOf(
        "8 Ball",
        "Abuelita",
        "Agent Powers",
        "Agent Trigger",
        "Alex Hirsch",
        "America Guy",
        "Amorphous Shape",
        "Anti-Mabel",
        "Aquatic Restaurant Cook",
        "Bat Boy",
        "Bats Biker",
        "Beardy",
        "BeeblyBoop's Clerk",
        "Bigfoot",
        "Bill Cipher",
        "Billy",
        "Billy's Mother",
        "Blendin Blandin",
        "Blind Ivan",
        "Bobby Renzobbi",
        "British Dog Man",
        "Bud Gleeful",
        "Bus Driver",
        "Candy Chiu",
        "Carla McCorkle",
        "Caryn Pines",
        "Charlie",
        "Charlie's Mother",
        "Cheekums",
        "Chutzpar",
        "Cinnamon",
        "Corduroy Brothers",
        "Crampelter",
        "Cycloptopus",
        "Darla Laudanum",
        "Davey",
        "Deputy Durland",
        "Deuce",
        "Dipper Pines",
        "Donald",
        "Donna",
        "Doug",
        "Dr. Karate",
        "Earl",
        "Emma Sue",
        "Emmaline Butternubbins",
        "Ergman Bratsman",
        "Ernesto",
        "Fertilia Mecc",
        "Filbrick Pines",
        "Ford Pines",
        "Gabe Benson",
        "Gary",
        "Ghost-Eyes",
        "Gideon Gleeful",
        ".GIFfany",
        "Gompers",
        "Gorney",
        "Grady Mecc",
        "Granny Sweetkin",
        "Grenda Grendinator",
        "Gus Gunderson",
        "Hand Witch",
        "Hank",
        "Harry Claymore",
        "Hectorgon",
        "Hot Elf",
        "Jean-Luc",
        "Jimmy",
        "Justin Kerprank",
        "Keyhole",
        "Killbone",
        "Kryptos",
        "Leaderaur",
        "Lee",
        "Lolph",
        "Mabel Pines",
        "Madeline Dixon",
        "Manly Dan",
        "Mariah",
        "Marius von Fundshauser",
        "Mattress King",
        "Mayor Befufftlefumpter",
        "Melody",
        "Meredith",
        "Mermando",
        "Mikey R.",
        "Modoc the Wise",
        "Mr. Poolcheck",
        "Mrs. Gleeful",
        "Multi-Bear",
        "Multilevel Mark",
        "Mummy Kid",
        "Nate",
        "Nathaniel Northwest",
        "Nicolas",
        "Octavia",
        "Old Man McGucket",
        "Paci-Fire",
        "Pacifica Northwest",
        "Paper Jam Dipper",
        "Pituitaur",
        "Pizza Guy",
        "Polly",
        "Pop Pop",
        "Preston Northwest",
        "Priscilla Northwest",
        "Probabilitor the Annoying",
        "Pubetor",
        "Pyronica",
        "Queen of the Manatees",
        "Quentin Trembley",
        "Questiony The Question Mark",
        "Reggie",
        "Reginald",
        "Rich",
        "Robbie Valentino",
        "Rosanna",
        "Santiago",
        "Sarcasti-Pup",
        "Sassica",
        "Sergei",
        "Shandra Jimenez",
        "Sheriff Blubs",
        "Shmipper"
    )

    val locations = listOf(
        "Backupsmore University",
        "BillVille",
        "Corn Maze",
        "Crash Site Omega",
        "Euclydia",
        "Globnar",
        "Globnar Stadium",
        "Granny Sweetkin's Yarnball",
        "Infinetentiary",
        "MAB-3L",
        "Mystery Fair",
        "Mystery Mountain",
        "Nightmare Realm",
        "Shacktron",
        "StanCo",
        "The Crawlspace",
        "Theraprism",
        "Upside-Down Town",
        "West Coast Tech"
    )

    val companies = listOf(
        // Major Businesses
        "Mystery Shack",
        "Tent of Telepathy",
        "Gleeful's Auto Sale",
        "Northwest Mud Flaps",
        // Retail Stores
        "Gravity Falls Mall",
        "Dusk 2 Dawn",
        "Skull Fracture",
        "Ye Royal Discount Putt Hutt",
        "Summerween Superstore",
        "Hermanos Brothers",
        "Edgy On Purpose",
        "Gary's Games and Stuff",
        // Food Services
        "Greasy's Diner",
        "Yumberjacks",
        "Smokey Joe's All-You-Can-Eat",
        "Hoo-Ha Owl's Pizzamatronic Jamboree",
        "Hermanos Brothers",
        "The Club",
        // Entertainment
        "Gravity Falls Gossiper",
        "Gravity Falls Public Access TV",
        "The Royal Order of the Holy Mackerel",
        "Lake Gravity Falls Fishing Season",
        // Local Services
        "Gravity Falls Hospital",
        "Gravity Falls Dump",
        "Gravity Falls Library",
        "Gravity Falls Prison",
        // Tourist Traps
        "Mystery Mountain",
        "Upside-Down Town",
        "Log Land",
        "Petting Zoo",
        // Fictional Brands
        "Pitt Cola",
        "Smile Dip",
        "Taco Time",
        "Cookie Chips",
        // Shops in the Mall
        "Build A Beaver",
        "Overalls Are Cool Now",
        "BeeblyBoop's Videogames",
        // Other Businesses
        "Big Gunz Laser Tag",
        "Mattress Prince's Amazing Mattress Store",
        "Mystery Mountain",
        "Pool Supply Store",
        "Gravity Falls Civic Center and Buffet",
        "Gravity Falls Boxing Gym",
        "Barrels & Crates, Incorporated"
    )
}