package elias.fakerMaker.fakers.tvshow

object Pokemon {

    val characters = listOf(
        // Main Human Characters
        "Ash Ketchum",
        "Misty",
        "Brock",
        "Delia Ketchum",
        "Professor Oak",
        "Gary Oak",
        // Team Rocket
        "Jessie",
        "James",
        "Meowth",
        "Giovanni",
        "Butch",
        "Cassidy",
        // Recurring Characters
        "Nurse Joy",
        "Officer Jenny",
        "Todd Snap",
        "Duplica",
        "AJ",
        "Melvin",
        "Damian",
        "Bill",
        "Professor Ivy",
        "Tracey Sketchit",
        "Richie",
        // Gym Leaders
        "Lt. Surge",
        "Erika",
        "Koga",
        "Sabrina",
        "Blaine",
        // Elite Four
        "Lorelei",
        "Bruno",
        "Agatha",
        "Lance",
        // Ash's Notable Pokémon
        "Pikachu",
        "Charizard",
        "Bulbasaur",
        "Squirtle",
        "Pidgeotto",
        "Butterfree",
        "Kingler",
        "Primeape",
        "Muk",
        "Tauros",
        "Snorlax",
        "Lapras",
        // Misty's Notable Pokémon
        "Staryu",
        "Starmie",
        "Goldeen",
        "Psyduck",
        "Togepi",
        // Brock's Notable Pokémon
        "Onix",
        "Geodude",
        "Zubat",
        "Vulpix",
        // Team Rocket's Notable Pokémon
        "Arbok",
        "Weezing",
        "Victreebel",
        "Wobbuffet",
        "Lickitung",
        // Legendary/Mythical Pokémon Featured
        "Mewtwo",
        "Mew",
        "Articuno",
        "Zapdos",
        "Moltres",
        "Lugia",
        "Ho-Oh",
        "Entei",
        "Suicune",
        "Raikou",
        // Other Notable Pokémon
        "Dragonite" /* The giant one from Bill's lighthouse */,
        "Marowak" /* The ghost from Lavender Town */,
        "Jigglypuff" /* The recurring singer */,
        "Slowbro" /* The one from the beach episode */,
        "Magikarp" /* James's famous purchase */,
        "Gyarados" /* Evolution of James's Magikarp */,
        "Porygon" /* From the banned episode */,
        "Clefairy" /* From the Mt. Moon episode */,
        "Haunter" /* The playful one that helped against Sabrina */,
        "Charmander" /* The abandoned one that became Charizard */,
        "Squirtle" /* Leader of the Squirtle Squad */,
        // Rival's Notable Pokémon
        "Blastoise" /* Gary's starter */,
        "Umbreon" /* Gary's signature Pokémon later */,
        "Sparky" /* Richie's Pikachu */,
        "Zippo" /* Richie's Charmeleon */
    )

    val locations = listOf(
        // Kanto Region Cities and Towns
        "Pallet Town",
        "Viridian City",
        "Pewter City",
        "Cerulean City",
        "Vermilion City",
        "Lavender Town",
        "Celadon City",
        "Fuchsia City",
        "Saffron City",
        "Cinnabar Island",
        // Important Kanto Landmarks
        "Viridian Forest",
        "Mt. Moon",
        "Rock Tunnel",
        "Pokemon Tower",
        "Safari Zone",
        "Seafoam Islands",
        "Power Plant",
        "Victory Road",
        "Indigo Plateau",
        "Pokemon League HQ",
        // Notable Buildings/Locations
        "Professor Oak's Laboratory",
        "Viridian City Gym",
        "Pewter City Museum",
        "Cerulean Cave",
        "S.S. Anne",
        "Silph Co. Building",
        "Celadon Department Store",
        "Fighting Dojo",
        "Team Rocket HQ",
        "Bill's Lighthouse",
        // Orange Islands
        "Valencia Island",
        "Tangelo Island",
        "Mikan Island",
        "Navel Island",
        "Trovita Island",
        "Kumquat Island",
        "Pummelo Island",
        "Shamouti Island",
        "Pinkan Island",
        // Special Locations
        "Hidden Village",
        "Grandpa Canyon",
        "Pokemopolis",
        "Grampa Canyon",
        "Pokemon Tech School",
        "A.J.'s Gym",
        "Evolution Mountain",
        "Melvin's Magician's House",
        "Breeding Center",
        "Porta Vista",
        "Maiden's Peak",
        "Dark City",
        "Hop Hop Hop Town",
        "Scissor Street",
        "Sunnytown",
        "Sunny Town",
        "Chrysanthemum Island",
        "Mandarin Island",
        // Training Locations
        "Pokemon Center",
        "Battle Park",
        "Pokemon School",
        "Training Village",
        "Evolution Stone Cave",
        "Giant Pokemon Island",
        "Pokémon Ninja School",
        "Pokemon Racing Track",
        "Pokemon Performance Stage"
    )

}