package elias.fakerMaker.fakers.videogames

object Halo {

    val characters = listOf(
        // UNSC Characters
        "Master Chief (John-117)",
        "Cortana",
        "Captain Jacob Keyes",
        "Commander Miranda Keyes",
        "Sergeant Avery Johnson",
        "Catherine Halsey",
        "Captain Thomas Lasky",
        "Sarah Palmer",
        "Edward Buck",
        "James Locke",
        // Other Spartans
        "Kelly-087",
        "Linda-058",
        "Fred-104",
        "Kurt-051",
        "Noble Six (B312)",
        "Carter-A259",
        "Jorge-052",
        "Emile-A239",
        "Jun-A266",
        "Kat-B320",
        // The Covenant
        "Arbiter (Thel 'Vadam)",
        "Tartarus",
        "Prophet of Truth",
        "Prophet of Regret",
        "Prophet of Mercy",
        "Rtas 'Vadum",
        "Jul 'Mdama",
        // The Banished
        "Atriox",
        "Escharum",
        "War Chief Lethari",
        // Forerunners
        "Didact",
        "Librarian",
        "343 Guilty Spark",
        "2401 Penitent Tangent",
        // The Created
        "The Weapon",
        "Despondent Pyre",
        // Insurrectionists/Others
        "Colonel Robert Watts",
        "Soren-066",
        "Makovich",
        "Mickey",
        "Echo-216 (Fernando Esparza)",
        // The Endless
        "Harbinger",
        "Xalanyn",
        // Spirit of Fire Crew
        "Captain James Cutter",
        "Professor Ellen Anders",
        "Serina",
        "Isabel",
        "Jerome-092",
        "Alice-130",
        "Douglas-042"
    )

    val locations = listOf(
        // Forerunner Installations
        "The Lesser Ark",
        "Shield World Trevelyan",
        "Requiem",
        "Genesis",
        "Threshold",
        "Bastion",
        // Human Worlds
        "Earth",
        "Reach",
        "Harvest",
        "Tribute",
        "Arcadia",
        "Paris IV",
        "Meridian",
        "Draco III",
        "Circumstance",
        "Coral",
        "New Alexandria",
        "New Mombasa",
        "Old Mombasa",
        "Voi",
        "Sydney",
        "Chicago",
        "Cleveland",
        "Mars",
        "Luna",
        // Covenant Locations
        "High Charity",
        "Sanghelios",
        "Doisac",
        "Balaho",
        "Te",
        "Eayn",
        "Palamok",
        "Janjur Qom",
        "Sunaion",
        "Stoic Courier",
        // Space Stations & Ships
        "Cairo Station",
        "Malta Station",
        "Athens Station",
        "UNSC Infinity",
        "Pillar of Autumn",
        "Spirit of Fire",
        "Forward Unto Dawn",
        "In Amber Clad",
        "Gettysburg",
        "Anchor 9",
        "Gamma Station",
        // Other Notable Locations
        "Apex",
        "The Quarantine Zone",
        "The Library",
        "The Control Room",
        "The Silent Cartographer",
        "The Maw",
        "Flood Containment Facility",
        "Two Betrayals",
        "Sword Base",
        "ONI Sword Base",
        "CASTLE Base",
        "Infinity's Armory",
        "The Pit",
        "Lockout",
        "Blood Gulch",
        "Valhalla",
        "Zanzibar",
        "Construct",
        "Foundry",
        "Haven"
    )

    val vehicles = listOf(
        "Warthog",
        "Scorpion",
        "Grizzly",
        "Kodiak",
        "Mongoose",
        "Cobra",
        "Elephant",
        "Mammoth",
        "Pelican",
        "Condor",
        "Falcon",
        "Hornet",
        "Sparrowhawk",
        "Wasp",
        "Longsword",
        "Shortsword",
        "Sabre",
        "Vulture",
        "Chopper",
        "Wraith",
        "Shadow",
        "Locust",
        "Ghost",
        "Spectre",
        "Scarab",
        "Revenant",
        "Prowler",
        "Banshee",
        "Seraph",
        "Phantom",
        "Spirit",
        "Kraken",
        "Lich",
        "Sentinel",
        "Constructor",
        "Phaeton",
        "Marauder",
        "Shroud",
        "Goblin",
        "Blisterback",
        "Spade",
        "Genet",
        "Forklift"
    )

    val weapons = listOf(
        // UNSC Weapons
        "Assault Rifle",
        "Battle Rifle",
        "DMR",
        "Magnum",
        "Sidekick",
        "SMG",
        "Sniper Rifle",
        "Shotgun",
        "Bulldog",
        "Rocket Launcher",
        "Spartan Laser",
        "Hydra",
        "SAW",
        "Railgun",
        "Grenade Launcher",
        "Target Locator",
        "Machine Gun Turret",
        "Chaingun",
        "Commando",
        "Tactical Shotgun",
        // Covenant Weapons
        "Plasma Pistol",
        "Plasma Rifle",
        "Needler",
        "Carbine",
        "Beam Rifle",
        "Energy Sword",
        "Fuel Rod Gun",
        "Brute Shot",
        "Spiker",
        "Mauler",
        "Plasma Turret",
        "Focus Rifle",
        "Concussion Rifle",
        "Gravity Hammer",
        "Plasma Launcher",
        "Needle Rifle",
        "Storm Rifle",
        // Banished Weapons
        "Skewer",
        "Ravager",
        "Stalker Rifle",
        "Mangler",
        "Pulse Carbine",
        "Shock Rifle",
        "Disruptor",
        "Cindershot",
        "Heatwave",
        // Throwables/Explosives
        "Frag Grenade",
        "Plasma Grenade",
        "Spike Grenade",
        "Firebomb Grenade",
        "Pulse Grenade",
        "Dynamo Grenade",
        "Mine",
        // Special/Power Weapons
        "Golf Club",
        "Energy Stave",
        "Flamethrower",
        "Focus Cannon",
        "Scarab Gun"
    )

}