package elias.fakerMaker.fakers.videogame

object SmashBros {

    val characters = listOf(
        // Original 8 (Smash 64)
        "Mario",
        "Donkey Kong",
        "Link",
        "Samus",
        "Yoshi",
        "Kirby",
        "Fox",
        "Pikachu",
        // Unlockable in Smash 64
        "Luigi",
        "Captain Falcon",
        "Ness",
        "Jigglypuff",
        // Added in Melee
        "Peach",
        "Bowser",
        "Ice Climbers",
        "Sheik",
        "Zelda",
        "Dr. Mario",
        "Pichu",
        "Falco",
        "Marth",
        "Young Link",
        "Ganondorf",
        "Mewtwo",
        "Roy",
        "Mr. Game & Watch",
        // Added in Brawl
        "Meta Knight",
        "Pit",
        "Zero Suit Samus",
        "Wario",
        "Snake",
        "Ike",
        "Pokemon Trainer (Squirtle, Ivysaur, Charizard)",
        "Diddy Kong",
        "Lucas",
        "King Dedede",
        "Olimar",
        "R.O.B.",
        "Toon Link",
        "Wolf",
        "Sonic",
        // Added in Smash 4
        "Villager",
        "Mega Man",
        "Wii Fit Trainer",
        "Rosalina & Luma",
        "Little Mac",
        "Greninja",
        "Palutena",
        "Pac-Man",
        "Robin",
        "Shulk",
        "Bowser Jr.",
        "Duck Hunt",
        "Ryu",
        "Cloud",
        "Corrin",
        "Bayonetta",
        "Mii Brawler",
        "Mii Swordfighter",
        "Mii Gunner",
        // Added in Ultimate Base Game
        "Daisy",
        "Ridley",
        "Simon",
        "Richter",
        "Chrom",
        "Dark Samus",
        "King K. Rool",
        "Isabelle",
        "Incineroar",
        "Ken",
        "Inkling",
        // Ultimate Fighter Pass Vol. 1 DLC
        "Piranha Plant",
        "Joker",
        "Hero",
        "Banjo & Kazooie",
        "Terry",
        "Byleth",
        // Ultimate Fighter Pass Vol. 2 DLC
        "Min Min",
        "Steve/Alex",
        "Sephiroth",
        "Pyra/Mythra",
        "Kazuya",
        "Sora"
    )
}