package elias.fakerMaker.fakers.books

object GameOfThrones {
    val characters = listOf(
        // Major Houses - Stark Extended
        "Rickard Stark",
        "Brandon Stark",
        "Torrhen Stark",
        "Cregan Stark",
        "Rodrik Cassel",
        "Jory Cassel",
        "Vayon Poole",
        "Jeyne Poole",
        "Old Nan",
        "Mikken",
        "Farlen",
        "Hullen",
        "Joseth",
        "Septa Mordane",
        // Lannister Extended
        "Stafford Lannister",
        "Daven Lannister",
        "Damion Lannister",
        "Willem Lannister",
        "Martyn Lannister",
        "Joanna Lannister",
        "Genna Lannister",
        "Cleos Frey",
        "Tyrek Lannister",
        "Joy Hill",
        // Targaryen Extended
        "Aegon I",
        "Visenya",
        "Rhaenys",
        "Aemon",
        "Jaehaerys I",
        "Alysanne",
        "Daemon",
        "Baelor I",
        "Daeron I",
        "Aegon IV",
        "Daemon Blackfyre",
        "Bloodraven",
        "Bittersteel",
        "Maester Aemon",
        "Aegon V",
        "Duncan",
        "Aerion Brightflame",
        "Maegor I",
        "Jaehaerys II",
        // Northern Houses
        "Greatjon Umber",
        "Smalljon Umber",
        "Rickard Karstark",
        "Harrion Karstark",
        "Alys Karstark",
        "Galbart Glover",
        "Robett Glover",
        "Howland Reed",
        "Maege Mormont",
        "Dacey Mormont",
        "Wyman Manderly",
        "Wylis Manderly",
        "Wendel Manderly",
        "Medger Cerwyn",
        "Barbrey Dustin",
        "Roger Ryswell",
        "Bethany Bolton",
        // Iron Islands
        "Victarion Greyjoy",
        "Urrigon Greyjoy",
        "Quellon Greyjoy",
        "Dagmer Cleftjaw",
        "Asha Greyjoy",
        "Rodrik Harlaw",
        "Erik Ironmaker",
        "Tristifer Botley",
        "Aeron Damphair",
        // Riverlands Houses
        "Tytos Blackwood",
        "Lucas Blackwood",
        "Jonos Bracken",
        "Jason Mallister",
        "Patrek Mallister",
        "Clement Piper",
        "Marq Piper",
        "Karyl Vance",
        "Ronald Vance",
        "Hugo Vance",
        // Vale Houses
        "Yohn Royce",
        "Andar Royce",
        "Robar Royce",
        "Nestor Royce",
        "Myranda Royce",
        "Anya Waynwood",
        "Morton Waynwood",
        "Donnel Waynwood",
        "Horton Redfort",
        "Jasper Redfort",
        "Benedar Belmore",
        "Symond Templeton",
        "Lyn Corbray",
        "Lucas Corbray",
        // Reach Houses
        "Randyll Tarly",
        "Dickon Tarly",
        "Paxter Redwyne",
        "Horas Redwyne",
        "Hobber Redwyne",
        "Arwyn Oakheart",
        "Mathis Rowan",
        "Jon Fossoway",
        "Tanton Fossoway",
        "Garlan Tyrell",
        "Willas Tyrell",
        "Luthor Tyrell",
        "Moryn Tyrell",
        "Gormon Tyrell",
        // Dorne Extended
        "Arianne Martell",
        "Quentyn Martell",
        "Obara Sand",
        "Nymeria Sand",
        "Tyene Sand",
        "Sarella Sand",
        "Elia Sand",
        "Obella Sand",
        "Dorea Sand",
        "Loreza Sand",
        "Anders Yronwood",
        "Quentyn Qorgyle",
        "Deziel Dalt",
        "Sylva Santagar",
        "Daemon Sand",
        // Essos Extended
        "Magister Illyrio",
        "Khal Jhaqo",
        "Khal Pono",
        "Kraznys mo Nakloz",
        "Grazdan mo Ullhor",
        "Brown Ben Plumm",
        "Salladhor Saan",
        "Moqorro",
        "Archmaester Marwyn",
        "Alleras",
        "Leo Tyrell",
        "Pate",
        "Kojja Mo",
        "Strong Belwas",
        "The Tattered Prince",
        "Pretty Meris",
        // Free Cities
        "Tycho Nestoris",
        "Noho Dimittis",
        "Bessaro",
        "Moredo Prestayn",
        "Ferrego Antaryon",
        "Tormo Fregar",
        "Nyessos Vhassar",
        // Night's Watch Extended
        "Donal Noye",
        "Denys Mallister",
        "Cotter Pyke",
        "Bedwyck",
        "Dywen",
        "Ulmer",
        "Kedge Whiteye",
        "Deaf Dick Follard",
        "Halder",
        "Albett",
        "Dareon",
        "Chett",
        "Clydas",
        "Othell Yarwyck",
        // Sellswords/Warriors
        "Vargo Hoat",
        "Timeon",
        "Shagwell",
        "Zollo",
        "Rorge",
        "Biter",
        "Gerris Drinkwater",
        "Archibald Yronwood",
        "Bloodbeard",
        "Gylo Rhegan",
        "Dick Straw",
        "Hugh Hungerford",
        // Religious Figures
        "Septon Meribald",
        "Elder Brother",
        "Septon Cellador",
        "Septa Unella",
        "Moelle",
        "Scolera",
        "The Waif",
        "Umma",
        "The Kindly Man",
        "Thoros of Myr",
        // Maesters
        "Luwin",
        "Cressen",
        "Colemon",
        "Gormon",
        "Ebrose",
        "Norren",
        "Mullin",
        "Theomore",
        "Harmune",
        "Tothmure",
        "Ballabar",
        "Gulian",
        "Nymos",
        "Wendamyr",
        // Common Folk/Others
        "Masha Heddle",
        "Tobho Mott",
        "Chataya",
        "Alayaya",
        "Dancy",
        "Mhaegen",
        "Mycah",
        "Lommy Greenhands",
        "Lady Stoneheart",
        "Tom of Sevenstreams",
        "Anguy",
        "High Spider",
        "Brown Bernarr",
        "Luke of Longtown",
        "Notch",
        "Mudge",
        "Beardless Dick",
        // Giants and Special Characters
        "Wun Wun",
        "Mag the Mighty",
        "Dongo",
        "Hodor",
        "Summer",
        "Grey Wind",
        "Lady",
        "Nymeria",
        "Ghost",
        "Shaggydog",
        "Drogon",
        "Rhaegal",
        "Viserion",
        "Old Nan",
        "High Heart Woods Witch",
        "Coldhands",
        "Three-Eyed Crow",
        "Leaf",
        "Children of the Forest",
        // Brotherhood Without Banners
        "Beric Dondarrion",
        "Lem Lemoncloak",
        "Jack-Be-Lucky",
        "Harwin",
        "Greenbeard",
        "Pello of Tyrosh",
        "Dennett",
        "Likely Luke",
        "Notch",
        "Anguy",
        // The Mountain's Men
        "Dunsen",
        "Polliver",
        "Raff the Sweetling",
        "The Tickler",
        "Chiswyck",
        "Eggon",
        "Tobbot",
        // Northern Characters
        "Mors Umber",
        "Hother Umber",
        "Crowfood",
        "Whoresbane",
        "Big Bucket Wull",
        "Hugo Wull",
        "Torghen Flint",
        "Black Donnel Flint",
        "Brandon Norrey",
        "Morgan Liddle",
        // Beyond the Wall
        "Varamyr Sixskins",
        "Thistle",
        "Mother Mole",
        "The Lord of Bones",
        "Styr",
        "Sigorn",
        "Harma Dogshead",
        "The Weeper",
        "Alfyn Crowkiller",
        "Dalla",
        "Val",
        // Slavers Bay
        "Cleon the Butcher King",
        "Brown Ben Plumm",
        "Reznak mo Reznak",
        "Skahaz mo Kandaq",
        "Galazza Galare",
        "Hizdahr zo Loraq",
        "Yurkhaz zo Yunzak",
        "Yezzan zo Qaggaz",
        // Iron Islands
        "Nute the Barber",
        "Left-Hand Lucas Codd",
        "Red Ralf Stonehouse",
        "Ralf the Limper",
        "Qarl the Maid",
        "Cromm",
        "Werlag",
        "Alvyn Sharp",
        "Grimtongue",
        // King's Landing
        "Moon Boy",
        "Butterbumps",
        "Hamish the Harper",
        "Jalabhar Xho",
        "Aurane Waters",
        "Orton Merryweather",
        "Taena Merryweather",
        "Gyles Rosby",
        "Tanda Stokeworth",
        "Lollys Stokeworth",
        // Brave Companions
        "Utt",
        "Septon Utt",
        "Three Toes",
        "Fat Zollo",
        "Togg Joth",
        "Qyburn",
        // Summer Islands
        "Xhondo",
        "Quhuru Mo",
        "Kojja Mo",
        // Others
        "Penny",
        "Groat",
        "Oppo",
        "Jinglebell",
        "Patchface",
        "Lady Lu",
        "Dick Crabb",
        "Nimble Dick",
        "Squint",
        "Mudge",
        "Wat",
        "Ben Bones",
        "Yellow Dick",
        "Sour Alyn",
        "Luton",
        "Grunt",
    )

    val houses = listOf(
        // Great Houses
        "House Stark of Winterfell",
        "House Lannister of Casterly Rock",
        "House Baratheon of Storm's End",
        "House Targaryen of King's Landing",
        "House Arryn of the Eyrie",
        "House Tully of Riverrun",
        "House Greyjoy of Pyke",
        "House Tyrell of Highgarden",
        "House Martell of Sunspear",
        // North
        "House Bolton of the Dreadfort",
        "House Karstark of Karhold",
        "House Umber of Last Hearth",
        "House Manderly of White Harbor",
        "House Reed of Greywater Watch",
        "House Glover of Deepwood Motte",
        "House Mormont of Bear Island",
        "House Cerwyn of Castle Cerwyn",
        "House Dustin of Barrowton",
        "House Hornwood",
        "House Tallhart",
        "House Flint",
        "House Locke",
        "House Ryswell",
        // Iron Islands
        "House Harlaw of Ten Towers",
        "House Blacktyde",
        "House Botley",
        "House Drumm",
        "House Goodbrother",
        "House Orkwood",
        "House Saltcliffe",
        "House Volmark",
        // Vale
        "House Royce of Runestone",
        "House Waynwood",
        "House Redfort",
        "House Belmore",
        "House Templeton",
        "House Hunter",
        "House Corbray",
        "House Grafton",
        "House Lynderly",
        "House Moore",
        // Riverlands
        "House Frey of the Twins",
        "House Blackwood of Raventree Hall",
        "House Bracken of Stone Hedge",
        "House Mallister of Seagard",
        "House Mooton",
        "House Piper",
        "House Vance",
        "House Whent",
        "House Darry",
        "House Smallwood",
        // Westerlands
        "House Clegane",
        "House Lefford",
        "House Crakehall",
        "House Marbrand",
        "House Brax",
        "House Banefort",
        "House Prester",
        "House Westerling",
        "House Swyft",
        "House Payne",
        // Reach
        "House Tarly of Horn Hill",
        "House Florent",
        "House Hightower",
        "House Redwyne",
        "House Rowan",
        "House Oakheart",
        "House Fossoway",
        "House Ashford",
        "House Crane",
        "House Merryweather",
        // Stormlands
        "House Dondarrion",
        "House Swann",
        "House Tarth",
        "House Selmy",
        "House Estermont",
        "House Caron",
        "House Connington",
        "House Penrose",
        "House Trant",
        "House Wylde",
        // Dorne
        "House Yronwood",
        "House Dayne of Starfall",
        "House Blackmont",
        "House Qorgyle",
        "House Allyrion",
        "House Manwoody",
        "House Jordayne",
        "House Santagar",
        "House Fowler",
        "House Uller",
        // Crownlands
        "House Velaryon",
        "House Celtigar",
        "House Sunglass",
        "House Bar Emmon",
        "House Massey",
        "House Rambton",
        "House Stokeworth",
        "House Rosby",
        "House Darklyn",
        "House Rykker",
    )
}