package elias.fakerMaker.fakers.books

object HarryPotter {
    val characters = listOf(
        // Main Trio and Family
        "Harry Potter",
        "Ronald Weasley",
        "Hermione Granger",
        "James Potter",
        "Lily Potter",
        "Petunia Dursley",
        "Vernon Dursley",
        "Dudley Dursley",
        // Hogwarts Staff
        "Albus Dumbledore",
        "Minerva McGonagall",
        "Severus Snape",
        "Rubeus Hagrid",
        "Filius Flitwick",
        "Pomona Sprout",
        "Sybill Trelawney",
        "Rolanda Hooch",
        "Argus Filch",
        "Poppy Pomfrey",
        "Irma Pince",
        "Aurora Sinistra",
        "Charity Burbage",
        "Septima Vector",
        "Horace Slughorn",
        "Gilderoy Lockhart",
        "Remus Lupin",
        "Alastor Moody",
        "Dolores Umbridge",
        "Quirinus Quirrell",
        // Death Eaters
        "Tom Riddle",
        "Bellatrix Lestrange",
        "Lucius Malfoy",
        "Narcissa Malfoy",
        "Draco Malfoy",
        "Peter Pettigrew",
        "Barty Crouch Jr",
        "Antonin Dolohov",
        "Fenrir Greyback",
        "Rodolphus Lestrange",
        "Rabastan Lestrange",
        "Augustus Rookwood",
        "Yaxley",
        "Travers",
        "Igor Karkaroff",
        "Evan Rosier",
        "Wilkes",
        "Avery",
        "Mulciber",
        "Nott",
        // Order of the Phoenix
        "Sirius Black",
        "Nymphadora Tonks",
        "Kingsley Shacklebolt",
        "Arthur Weasley",
        "Molly Weasley",
        "Bill Weasley",
        "Charlie Weasley",
        "Fred Weasley",
        "George Weasley",
        "Percy Weasley",
        "Ginny Weasley",
        "Arabella Figg",
        "Elphias Doge",
        "Dedalus Diggle",
        "Emmeline Vance",
        "Sturgis Podmore",
        "Hestia Jones",
        "Mundungus Fletcher",
        "Alice Longbottom",
        "Frank Longbottom",
        // Hogwarts Students
        "Neville Longbottom",
        "Luna Lovegood",
        "Seamus Finnigan",
        "Dean Thomas",
        "Lavender Brown",
        "Parvati Patil",
        "Padma Patil",
        "Cho Chang",
        "Michael Corner",
        "Terry Boot",
        "Anthony Goldstein",
        "Hannah Abbott",
        "Susan Bones",
        "Justin Finch-Fletchley",
        "Ernie Macmillan",
        "Theodore Nott",
        "Blaise Zabini",
        "Pansy Parkinson",
        "Vincent Crabbe",
        "Gregory Goyle",
        "Millicent Bulstrode",
        "Colin Creevey",
        "Dennis Creevey",
        "Lee Jordan",
        "Angelina Johnson",
        "Katie Bell",
        "Alicia Spinnet",
        "Oliver Wood",
        "Marcus Flint",
        "Cedric Diggory",
        "Marietta Edgecombe",
        // Ministry of Magic
        "Cornelius Fudge",
        "Rufus Scrimgeour",
        "Pius Thicknesse",
        "Barty Crouch Sr",
        "Ludo Bagman",
        "Amelia Bones",
        "John Dawlish",
        "Gawain Robards",
        "Percy Weasley",
        "Mafalda Hopkirk",
        "Rita Skeeter",
        // Magical Creatures and Beings
        "Dobby",
        "Kreacher",
        "Winky",
        "Griphook",
        "Firenze",
        "Ronan",
        "Bane",
        "Aragog",
        "Buckbeak",
        "Fawkes",
        "Nagini",
        "Hedwig",
        "Crookshanks",
        "Pigwidgeon",
        // Others
        "Aberforth Dumbledore",
        "Ariana Dumbledore",
        "Kendra Dumbledore",
        "Percival Dumbledore",
        "Nicolas Flamel",
        "Perenelle Flamel",
        "Gellert Grindelwald",
        "Bathilda Bagshot",
        "Xenophilius Lovegood",
        "Madam Rosmerta",
        "Tom (Leaky Cauldron)",
        "Florean Fortescue",
        "Mr. Ollivander",
        "Madam Malkin",
        "Stan Shunpike",
        "Viktor Krum",
        "Fleur Delacour",
        "Gabrielle Delacour",
        "Madame Maxime",
        "Igor Karkaroff",
        "Gregorovitch",
        "Grawp",
        "Aunt Muriel",
        "Scabior",
        "Grindelwald",
        // Named Pets
        "Scabbers",
        "Mrs. Norris",
        "Crookshanks",
        "Hedwig",
        "Pigwidgeon",
        "Errol",
        "Hermes",
        "Fawkes",
        "Trevor",
        "Nagini",
        "Arnold",
        "Buckbeak",
        "Witherwings",
        "Fang",
        "Fluffy",
        "Norbert",
        "Norberta",
        "Aragog",
        "Mosag",
        "Tenebrus"
    )

    val companies = listOf(
        // Diagon Alley Shops
        "Gringotts Wizarding Bank",
        "Ollivanders",
        "Flourish and Blotts",
        "Quality Quidditch Supplies",
        "Madam Malkin's Robes for All Occasions",
        "Eeylops Owl Emporium",
        "Florean Fortescue's Ice Cream Parlour",
        "Magical Menagerie",
        "Slug & Jiggers Apothecary",
        "Twilfitt and Tattings",
        "Wiseacre's Wizarding Equipment",
        "Gambol and Japes Wizarding Joke Shop",
        // Knockturn Alley Shops
        "Borgin and Burkes",
        "The Spiny Serpent",
        "Msaw Ætare",
        "Moribund's",
        // Hogsmeade Businesses
        "The Three Broomsticks",
        "Honeydukes",
        "Zonko's Joke Shop",
        "The Hog's Head",
        "Dervish and Banges",
        "Gladrags Wizardwear",
        "Scrivenshaft's Quill Shop",
        "Madam Puddifoot's Tea Shop",
        // Newspapers/Media
        "Daily Prophet",
        "The Quibbler",
        "Witch Weekly",
        "Wizarding Wireless Network",
        // Manufacturing
        "Cleansweep Broom Company",
        "Comet Trading Company",
        "Nimbus Racing Broom Company",
        "Firebolt Broom Company",
        "Flyte and Barker",
        // Food and Beverage
        "Butterbeer",
        "Ogden's Old Firewhisky",
        "Bertie Bott's Every Flavour Beans",
        "Drooble's Best Blowing Gum",
        "Chocolate Frogs",
        // Transportation
        "Knight Bus",
        "Hogwarts Express",
        "Floo Network Authority",
        // Entertainment
        "Weird Sisters",
        "Magical Entertainment",
        "British and Irish Quidditch League",
        // Weasley Enterprises
        "Weasleys' Wizard Wheezes",
        "Weasley's Wizard Wireless",
        // Ministry Departments (as organizations)
        "Department of Magical Law Enforcement",
        "Department of Magical Transportation",
        "Department of International Magical Cooperation",
        "Department for the Regulation and Control of Magical Creatures",
        "Department of Magical Games and Sports",
        // Healthcare
        "St Mungo's Hospital for Magical Maladies and Injuries",
        "Healers' Association",
        // Muggle Companies Mentioned
        "Grunnings",
        "Rail Track",
        "British Railways",
        // Professional Organizations
        "Wizengamot",
        "International Confederation of Wizards",
        "Order of Merlin",
        // Educational
        "Hogwarts School of Witchcraft and Wizardry",
        "Beauxbatons Academy of Magic",
        "Durmstrang Institute"
    )
}