package elias.fakerMaker.fakers.books

object LordOfTheRings {
    val characters = listOf(
        // Fellowship
        "Frodo Baggins",
        "Samwise Gamgee",
        "Meriadoc Brandybuck",
        "Peregrin Took",
        "Gandalf",
        "Aragorn",
        "Boromir",
        "Legolas",
        "Gimli",
        // Hobbits
        "Bilbo Baggins",
        "Fredegar Bolger",
        "Farmer Maggot",
        "Mrs. Maggot",
        "Old Noakes",
        "Daddy Twofoot",
        "Ham Gamgee",
        "Halfast Gamgee",
        "Rose Cotton",
        "Tolman Cotton",
        "Lily Cotton",
        "Rosie Cotton",
        "Nibs Cotton",
        "Ted Sandyman",
        "Lobelia Sackville-Baggins", "Otho Sackville-Baggins", "Will Whitfoot", "Robin Smallburrow",
        // Men
        "Denethor",
        "Faramir",
        "Théoden",
        "Éomer",
        "Éowyn",
        "Gríma Wormtongue",
        "Háma",
        "Gamling",
        "Erkenbrand",
        "Beregond",
        "Bergil",
        "Forlong",
        "Hirluin",
        "Imrahil",
        "Húrin",
        "Ingold",
        "Damrod",
        "Mablung",
        "Anborn",
        "Barliman Butterbur",
        "Bill Ferny",
        "Harry Goatleaf",
        // Elves
        "Elrond",
        "Arwen",
        "Glorfindel",
        "Galadriel",
        "Celeborn",
        "Haldir",
        "Rúmil",
        "Orophin",
        "Gildor Inglorion",
        "Erestor",
        // Evil Characters,
        "Sauron",
        "Saruman",
        "Witch-king",
        "Gollum/Sméagol",
        "Shelob",
        "Mouth of Sauron",
        "Grishnákh",
        "Uglúk",
        "Shagrat",
        "Gorbag",
        // Ancient/Historical
        "Isildur",
        "Elendil",
        "Gil-galad",
        "Anárion",
        "Eärnur",
        "Cirion",
        "Eorl",
        // Others
        "Tom Bombadil",
        "Goldberry",
        "Treebeard",
        "Quickbeam",
        "Skinbark",
        "Shadowfax",
        "Bill the Pony",
    )

    val locations = listOf(
        // Major Regions
        "Middle-earth",
        "Eriador",
        "Rhovanion",
        "Gondor",
        "Rohan",
        "Mordor",
        "Arnor",
        "Harad",
        "Rhûn",
        "Forodwaith",
        "Ered Luin",
        "Beleriand",
        // Kingdoms/Realms
        "The Shire",
        "Rivendell",
        "Lothlórien",
        "Mirkwood",
        "Erebor",
        "Khazad-dûm",
        "Angmar",
        "Númenor",
        "Valinor",
        "Undying Lands",
        // Cities/Strongholds
        "Minas Tirith",
        "Minas Morgul",
        "Osgiliath",
        "Edoras",
        "Helm's Deep",
        "Isengard",
        "Barad-dûr",
        "Dale",
        "Lake-town",
        "Hobbiton",
        "Bree",
        "Cair Andros",
        "Dol Amroth",
        // Mountains
        "Misty Mountains",
        "White Mountains",
        "Grey Mountains",
        "Iron Hills",
        "Mount Doom",
        "Caradhras",
        "Weathertop",
        "Mindolluin",
        "Erebor",
        "Mount Gram",
        // Forests
        "Fangorn Forest",
        "Old Forest",
        "Trollshaws",
        "Druadan Forest",
        "Firien Wood",
        "Chetwood",
        "Bindbole Wood",
        // Rivers
        "Anduin",
        "Brandywine",
        "Entwash",
        "Greyflood",
        "Isen",
        "Silverlode",
        "Withywindle",
        "Morgulduin",
        // Notable Locations
        "Bag End",
        "Brandy Hall",
        "Prancing Pony",
        "Golden Hall",
        "Black Gate",
        "Dead Marshes",
        "Emyn Muil",
        "Fords of Isen",
        "Gap of Rohan",
        "Gladden Fields",
        "Paths of the Dead",
        "Pelennor Fields",
        "Sammath Naur",
        "Tower Hills",
        "Weathertop",
        "Crack of Doom"
    )
}