package elias.fakerMaker.fakers.sports

object Baseball {
    val players = listOf(
        "Aaron Boone",
        "Aaron Judge",
        "Adam Dunn",
        "Adam Wainwright",
        "Adrian Beltre",
        "Al Kaline",
        "Al Simmons",
        "Albert Belle",
        "Albert Pujols",
        "Alejandro Kirk",
        "Alex Bregman",
        "Alex Rodriguez",
        "Alfonso Soriano",
        "Allie Reynolds",
        "Andre Dawson",
        "Andres Galarraga",
        "Andrew McCutchen",
        "Andruw Jones",
        "Andy Pettitte",
        "Anthony Rizzo",
        "Babe Ruth",
        "Barry Bonds",
        "Barry Larkin",
        "Bart Colon",
        "Ben Sheets",
        "Bernie Williams",
        "Bill Dickey",
        "Bill Mazeroski",
        "Bill Terry",
        "Billy Hamilton",
        "Billy Pierce",
        "Billy Wagner",
        "Billy Williams",
        "Bob Feller",
        "Bob Gibson",
        "Bobby Bonds",
        "Bobby Doerr",
        "Bobby Thomson",
        "Brandon Crawford",
        "Brandon Phillips",
        "Brandon Webb",
        "Brooks Robinson",
        "Bruce Sutter",
        "Buck Leonard",
        "Buddy Bell",
        "Buster Posey",
        "Cal Ripken Jr",
        "Carl Crawford",
        "Carl Hubbell",
        "Carl Yastrzemski",
        "Carlton Fisk",
        "Carmelo Martinez",
        "Casey Stengel",
        "CC Sabathia",
        "Cecil Cooper",
        "Cecil Fielder",
        "Charlie Gehringer",
        "Chase Utley",
        "Chipper Jones",
        "Chris Carpenter",
        "Chris Sale",
        "Chuck Klein",
        "Clayton Kershaw",
        "Cliff Lee",
        "Cole Hamels",
        "Cool Papa Bell",
        "Craig Biggio",
        "Curtis Granderson",
        "Cy Young",
        "Dale Murphy",
        "Dan Brouthers",
        "Dan Uggla",
        "Daniel Murphy",
        "Danny Darwin",
        "Dante Bichette",
        "Darrell Evans",
        "Dave Parker",
        "Dave Winfield",
        "David Cone",
        "David Justice",
        "David Ortiz",
        "David Price",
        "David Wright",
        "Dennis Eckersley",
        "Derek Jeter",
        "Derrek Lee",
        "Dick Allen",
        "Don Drysdale",
        "Don Mattingly",
        "Don Newcombe",
        "Don Sutton",
        "Dwight Evans",
        "Dwight Gooden",
        "Duke Snider",
        "Dustin Pedroia",
        "Early Wynn",
        "Eddie Collins",
        "Eddie Matthews",
        "Eddie Murray",
        "Edgar Martinez",
        "Ernie Banks",
        "Felix Hernandez",
        "Ferguson Jenkins",
        "Fernando Tatis Jr",
        "Fernando Valenzuela",
        "Frankie Frisch",
        "Frank Robinson",
        "Frank Thomas",
        "Fred Lynn",
        "Fred McGriff",
        "Freddie Freeman",
        "Gary Carter",
        "Gary Sheffield",
        "Gaylord Perry",
        "George Brett",
        "George Foster",
        "George Kell",
        "George Sisler",
        "Gio Gonzalez",
        "Goose Gossage",
        "Greg Maddux",
        "Grover Alexander",
        "Hack Wilson",
        "Hal Newhouser",
        "Hank Aaron",
        "Hank Greenberg",
        "Hanley Ramirez",
        "Harmon Killebrew",
        "Harold Baines",
        "Harry Heilmann",
        "Harvey Kuenn",
        "Heinie Manush",
        "Honus Wagner",
        "Hoyt Wilhelm",
        "Hunter Pence",
        "Ian Kinsler",
        "Ichiro Suzuki",
        "Ivan Rodriguez",
        "Jackie Robinson",
        "Jacob deGrom",
        "Jake Arrieta",
        "Jake Peavy",
        "Jason Giambi",
        "Jason Kendall",
        "Jeff Bagwell",
        "Jeff Kent",
        "Jeff Samardzija",
        "Jim Bunning",
        "Jim Edmonds",
        "Jim Palmer",
        "Jim Rice",
        "Jim Thome",
        "Jimmy Foxx",
        "Jimmy Rollins",
        "Joe Carter",
        "Joe Cronin",
        "Joe DiMaggio",
        "Joe Mauer",
        "Joe Medwick",
        "Joe Morgan",
        "Joe Torre",
        "Joey Votto",
        "John Olerud",
        "John Smoltz",
        "Johnny Bench",
        "Johnny Damon",
        "Johnny Mize",
        "Johnny Pesky",
        "Johnny Vander Meer",
        "Jon Lester",
        "Jorge Posada",
        "Jose Altuve",
        "Jose Bautista",
        "Jose Canseco",
        "Jose Fernandez",
        "Jose Reyes",
        "Josh Beckett",
        "Josh Donaldson",
        "Josh Gibson",
        "Josh Hamilton",
        "Juan Gonzalez",
        "Juan Marichal",
        "Juan Pierre",
        "Juan Soto",
        "Justin Morneau",
        "Justin Turner",
        "Justin Upton",
        "Justin Verlander",
        "Keith Hernandez",
        "Ken Boyer",
        "Ken Caminiti",
        "Ken Griffey Jr",
        "Kenny Lofton",
        "Kenny Rogers",
        "Kent Tekulve",
        "Kevin Brown",
        "Kevin Youkilis",
        "Kirby Puckett",
        "Kirk Gibson",
        "Lance Berkman",
        "Larry Doby",
        "Larry Walker",
        "Lloyd Waner",
        "Lou Brock",
        "Lou Gehrig",
        "Lou Whitaker",
        "Luis Aparicio",
        "Luis Gonzalez",
        "Luke Appling",
        "Manny Machado",
        "Manny Ramirez",
        "Mark Buehrle",
        "Mark McGwire",
        "Mark Teixeira",
        "Martin Prado",
        "Marty Marion",
        "Matt Cain",
        "Matt Holliday",
        "Matt Kemp",
        "Max Scherzer",
        "Mel Ott",
        "Michael Young",
        "Mickey Cochrane",
        "Mickey Mantle",
        "Mike Mussina",
        "Mike Piazza",
        "Mike Schmidt",
        "Mike Trout",
        "Minnie Minoso",
        "Mo Vaughn",
        "Moises Alou",
        "Nelson Cruz",
        "Nolan Arenado",
        "Nolan Ryan",
        "Omar Vizquel",
        "Orlando Cepeda",
        "Oscar Charleston",
        "Ozzie Smith",
        "Paul Goldschmidt",
        "Paul Konerko",
        "Paul Molitor",
        "Paul Waner",
        "Pedro Guerrero",
        "Pedro Martinez",
        "Pete Rose",
        "Phil Niekro",
        "Phil Rizzuto",
        "Prince Fielder",
        "Rafael Furcal",
        "Rafael Palmeiro",
        "Ralph Kiner",
        "Randy Johnson",
        "Ray Durham",
        "Red Ruffing",
        "Reggie Jackson",
        "Rich Gossage",
        "Roberto Alomar",
        "Roberto Clemente",
        "Robin Roberts",
        "Robin Ventura",
        "Robin Yount",
        "Robinson Cano",
        "Rod Carew",
        "Roger Clemens",
        "Roger Maris",
        "Rogers Hornsby",
        "Rollie Fingers",
        "Ron Cey",
        "Ron Guidry",
        "Ron Santo",
        "Roy Campanella",
        "Roy Halladay",
        "Roy Oswalt",
        "Ryne Sandberg",
        "Sam Crawford",
        "Sammy Sosa",
        "Sandy Koufax",
        "Satchel Paige",
        "Scott Rolen",
        "Stan Musial",
        "Steve Carlton",
        "Steve Garvey",
        "Ted Lyons",
        "Ted Simmons",
        "Ted Williams",
        "Tim Hudson",
        "Tim Lincecum",
        "Tim Raines",
        "Todd Helton",
        "Tom Glavine",
        "Tom Seaver",
        "Tony Gwynn",
        "Tony Perez",
        "Travis Hafner",
        "Trevor Hoffman",
        "Troy Glaus",
        "Troy Tulowitzki",
        "Tug McGraw",
        "Ty Cobb",
        "Victor Martinez",
        "Vladimir Guerrero",
        "Wade Boggs",
        "Warren Spahn",
        "Whitey Ford",
        "Will Clark",
        "Willie Davis",
        "Willie Horton",
        "Willie Mays",
        "Willie McCovey",
        "Willie Stargell",
        "Willie Wilson",
        "Yogi Berra",
        "Zack Greinke"
    )

    val teams = listOf(
        // American League East
        "Baltimore Orioles",
        "Boston Red Sox",
        "New York Yankees",
        "Tampa Bay Rays",
        "Toronto Blue Jays",
        // American League Central
        "Chicago White Sox",
        "Cleveland Guardians",
        "Detroit Tigers",
        "Kansas City Royals",
        "Minnesota Twins",
        // American League West
        "Houston Astros",
        "Los Angeles Angels",
        "Oakland Athletics",
        "Seattle Mariners",
        "Texas Rangers",
        // National League East
        "Atlanta Braves",
        "Miami Marlins",
        "New York Mets",
        "Philadelphia Phillies",
        "Washington Nationals",
        // National League Central
        "Chicago Cubs",
        "Cincinnati Reds",
        "Milwaukee Brewers",
        "Pittsburgh Pirates",
        "St. Louis Cardinals",
        // National League West
        "Arizona Diamondbacks",
        "Colorado Rockies",
        "Los Angeles Dodgers",
        "San Diego Padres",
        "San Francisco Giants",
        // Defunct Teams
        "Montreal Expos", // Now Washington Nationals
        "Cleveland Indians", // Now Cleveland Guardians
        "Florida Marlins", // Now Miami Marlins
        "Anaheim Angels", // Now Los Angeles Angels
        "California Angels", // Now Los Angeles Angels
        "Tampa Bay Devil Rays", // Now Tampa Bay Rays
        "Houston Colt .45s", // Now Houston Astros
        "Washington Senators", // Became Minnesota Twins
        "Milwaukee Braves", // Now Atlanta Braves
        "Brooklyn Dodgers", // Now Los Angeles Dodgers
        "New York Giants", // Now San Francisco Giants
        "Philadelphia Athletics", // Now Oakland Athletics
        "St. Louis Browns", // Now Baltimore Orioles
        "Boston Braves", // Eventually became Atlanta Braves
        "Montreal Royals", // Minor League team affiliated with Dodgers
        "Seattle Pilots" // Became Milwaukee Brewers
    )
}